Lissy93/dashy

- Dockerfile
- README.md
- entrypoint.sh
- package.json
- server.js
- yarn.lock
This PR includes a complete re-write of the Dockerfile.
The original one was pretty terrible, I had no idea what I was doing. It's a little bit better now. 
It should work.
> Fixing docker

- README.md
- package.json
- public/default.html
- server.js
- src/components/Configuration/ConfigContainer.vue
- src/components/Configuration/JsonEditor.vue
- src/utils/ConfigSchema.js
- src/utils/ConfigValidator.js
- yarn.lock
This PR includes:
- Writes a JSON schema
- Uses Ajv to validate users config against schema
- Implements validation into the build process
- Implements validation into the JSON editor in the UI
- Updates the readme
> Feature: Implements Configuration Validation

- src/components/PageStrcture/Footer.vue
**Issue Number** (if applicable):
None
**Briefly outline your changes**:
The footer link to viewing the source code sends users to the wrong repository. This repo must've been named "panel" in a past life, but now it is "dashy". This resolves the issue.
> fix: update link in footer with new repo name

- docs/configuring.md
- src/components/PageStrcture/Footer.vue
- Feature
**Issue Number** (if applicable): #28
**Briefly outline your changes**: Enables user to have HTML and inline styles rendered in the footer. Uses `v-html`.
Example usage:
```yaml
pageInfo:
title: Dashy
footerText: '<div style="text-align: left;"><h1 style="color: blue;">HTML Footer Example</h1><ul><li>Bullet 1</li><li>Bullet 2</li></ul></div>'
```
> Enables the user to add raw HTML and inline CSS into the footer, Re: #28

- docs/theming.md
- src/components/LinkItems/Item.vue
- src/components/LinkItems/StatusIndicator.vue
- src/styles/color-palette.scss
- src/styles/color-themes.scss
- Bugfix
**Issue Number** (if applicable): #39 
**Briefly outline your changes**:
The tooltips for status indicators were not visible in some themes. Fixed it by adding custom CSS variable so that themes can target the element correctly, and also added a class name so that the Material theme did not set `display: none` to the status indicator tooltip.
> [BUG-FIX] Status check tooltip visibility, Re: #39

- docker-compose.yml
**Issue Number** (if applicable): #48
**Briefly outline your changes**: There was a duplicate identifier, `environment` in the [`docker-compose.yml`](https://github.com/Lissy93/dashy/blob/master/docker-compose.yml#L19) file, as pointed out by @EVOTk in #48. This PR applies his suggestions, removing the duplicate key.
> [BUG-FIX] Removes duplicate Environment tag from docker-compose

- docs/status-indicators.md
- src/components/LinkItems/Item.vue
- src/components/LinkItems/ItemGroup.vue
- src/components/Settings/SettingsContainer.vue
- src/styles/color-themes.scss
- src/utils/ConfigSchema.json
- src/utils/defaults.js
- src/views/Login.vue
- Bugfix
- Feature
**Issue Number** (if applicable): #35 and #50 
**Briefly outline your changes**:
- Adds optional option to continuously check site status, Re: #35
- Fixed background color in login form, Re: #50 
- Adds a new Vapourwave theme
> [FEATURE] Continuous status checking

- src/components/LinkItems/Item.vue
- Bugfix
Fixes text alignment on tile title when in small mode.
Sets text-align and max-width on the small tiles. Thanks to @m4x91
**Issue Number**: #41
**New Vars**: N/A
> :bug: Re #41: Fixes small UI issue on tile-title

- package.json
- src/utils/Auth.js
- src/views/Login.vue
**Category**: Feature 
Previously the login was set to expire at the end of the users session, but Chromium browsers will suspend open tabs that are inactive for a certain period of time, to preserve memory, causing the session to expire prematurely, and you to be logged out. I see that this probably isn't the desirable behavior, so I will implement an option for the user to specify how long they'd like to stay logged in for, and this will be preserved even when the user closes their browser/ ends the session.
This small PR implements a dropdown menu, enabling the user to select how long they would like to stay logged in for. It then adds this value into the auth token's expiry, stored in the browser.
**Issue Number** #64
> If you've introduced any significant UI changes, …
> [FEATURE] Implements a 'Remember Me' dropdown to Login form

- docs/configuring.md
- src/App.vue
- src/components/PageStrcture/Header.vue
- src/components/Settings/SettingsContainer.vue
- src/router.js
- src/utils/ConfigAccumalator.js
- src/utils/ConfigHelpers.js
- src/utils/ConfigSchema.json
**Overview**
Adds several new attributes into the config (under `appConfig.hideComponents`) to enable users to disable components that they do not need or want. This includes: Heading, Nav menu, Search bar, Settings box and footer. Also moved the splash screen attr into this object for consistency. All components are visible by default, but the user can disable those they don't want on a per-component basis, using these options. Because of this, the update will not have any effect on users, until they add these values into their config file.
As well as the feature, I've also refactored the Config Accumulator, turning it from a series of functions, into a Class. This improves efficiency, as the config file is only processed once (when the class is initiated), rather …
> [FEATURE] Show hide components

- .github/pull_request_template.md
- package.json
- server.js
- services/config-validator.js
- services/update-checker.js
- src/utils/ConfigSchema.json
**Category**: Build update
**Overview**
- Added missing `appConfig.disableUpdateChecks` attribute to schema
- I forgot to do this in #101 
- Checks for updates when app builds
- Moves Schema checker into services directory
> [BUILD] - Adds update check in build process, and refactors

- README.md
- docs/configuring.md
- package.json
- src/components/PageStrcture/Header.vue
- src/components/PageStrcture/PageTitle.vue
- src/utils/ConfigAccumalator.js
- src/utils/ConfigSchema.json
**Overview**: Adds an optional attribute, `pageInfo.logo`, enabling the user to display a logo image in the apps header.
**Issue Number** #104
**New Vars**
- **`pageInfo.logo`** - `string` - _Optional_ 
- The path to an image to display in the header (to the right of the title). This can be either local, where `/` is the root of `./public`, or any remote image, such as `https://i.ibb.co/yhbt6CY/dashy.png`. It's recommended to scale your image down, so that it doesn't impact load times
**Screenshot**
[Link](https://user-images.githubusercontent.com/1862727/127051121-8f71d6aa-41e2-4b4a-8608-e03d39863375.png)
> [FEATURE] Add option for image in header, Re: #104

- .github/CHANGELOG.md
- README.md
- package.json
- src/App.vue
- src/components/Configuration/ConfigContainer.vue
- src/components/Settings/ConfigLauncher.vue
- src/components/Settings/ThemeSelector.vue
- src/utils/CoolConsole.js
- src/utils/ErrorHandler.js
- src/views/Home.vue
**Category**: Refactor
**Overview**
- Moves cloud sync dialog into the config menu, and removes icon on homepage
- Fixes typo in Default theme name, Re #106
- Spell checks readme
- Updates the contributor CI action, that generates list of contributors + sponsors
**Issue Number**  #106
> [REFACTOR] Spell check and reorganization

- .github/CHANGELOG.md
- package.json
- src/components/Configuration/JsonEditor.vue
- src/router.js
- src/utils/Auth.js
**Category**: 
> One of: Security
**Overview**
- Use both username + password for generating token, so that a change in either will log the user out
- Prevent privilege escalation by disallowing a user from modifying their user type through the UI
- Improve the isAuthenticated check, by taking account of empty users array 
> [SECURITY] Improve Robustness of Auth Checking

- .github/CHANGELOG.md
- package.json
- src/components/Configuration/ConfigContainer.vue
**Category**:   Minor / UI Bugfix
**Overview**
With some languages (e.g. French) the text is considerably longer. This caused issues with text wrapping onto the next line of the config container's buttons, which didn't look very neat. This PR fixes this, by making the width of the button equal to that of the longest line of text.
**Issue Number** #115
**Screenshot** 
> [FIX] Text overflows when language is very long

- .github/CHANGELOG.md
- .github/pr-badge.yml
- package.json
- src/components/Configuration/ConfigContainer.vue
- src/components/Settings/ThemeSelector.vue
- yarn.lock
A couple of minor UI issues were raised. This PR fixes those.
**Overview**
- ⬇️ Downgrades and pins vue-material-tabs to 0.1.5, to prevent breaking changes
- Fixes #118 p1
- 🩹 Sets auto-width for theme selector, so text doesn't wrap for long theme names
- Fixes  #119
- 🩹 Uses flex layout for config menu, so note doesn't overlap menu on small screens
- Fixes #118 p2
**Issue Number**  #118 and #119
> [FIX] Small UI Issues

- .github/CHANGELOG.md
- Dockerfile-arm32v7
- Dockerfile-arm64v8
- docs/deployment.md
- docs/developing.md
- package.json
**Overview**
The aim of this PR is to provide Docker support for the Raspberry Pi (models 2, 3, and 4+), as well as other ARM-based modern single-board computers. The majority of devices should be covered with `arm32v7` and `arm64v8` architectures.
**Issue Number**  #117
> [FEATURE] RPi Arm V7 & 8 Docker support

- Dockerfile
- Dockerfile-arm32v7
- Dockerfile-arm64v8
- hooks/pre-build
**Category**: 
Feature, Docker
**Overview**
Add two Dockerfiles for ARMv7 and ARMv8 builds such that Dashy can be deployed on Raspberry Pi's for instance.
See also PR #122 
**Issue Number**  #117
**New Vars**
The `hooks/pre-build` script has to be executed before building the images to enable QEMU.
> [FEATURE] RPi Arm V7 & 8 Docker support revisited

- .github/CHANGELOG.md
- package.json
- src/styles/color-themes.scss
- src/utils/defaults.js
**Category**: Theme addition
**Overview**
Very quick PR to add a new theme, which is used on a dashboard I am deploying
**Screenshot** 
> [THEME] - Adds new theme

- .github/CHANGELOG.md
- docs/authentication.md
- docs/configuring.md
- package.json
- src/components/Configuration/JsonEditor.vue
- src/components/LinkItems/ItemGroup.vue
- src/components/Settings/SettingsContainer.vue
- src/router.js
- src/utils/Auth.js
- src/utils/ConfigAccumalator.js
- src/utils/ConfigSchema.json
- src/views/Login.vue
**Overview**
Enables user to control which sections are visible to which users, including hiding sections for unauthenticated guest users
**Issue Number** #165
**New Vars** 
The following new attributes are listed under `sections.item[n].displayData`
- `hideForUsers` - Section will be visible to all users, except for those specified in this list
- `showForUsers` - Section will be hidden from all users, except for those specified in this list
- `hideForGuests` - Section will be visible for logged in users, but not for guests
> [FEATURE] Granular User Access

- docs/alternate-views.md
- docs/privacy.md
- docs/readme.md
- src/components/LinkItems/Section.vue
- src/utils/CheckSectionVisibility.js
- src/utils/ConfigHelpers.js
- src/views/Home.vue
**Overview**
#171 introduced granular user access, enabling certain sections to be hidden or shown to certain users. There was a mistake in the implementation, where the checking process was done on the Home view, and not in the main config accumulator, meaning that only sections within the Home view were correctly filtered. This PR fixes this, by moving the filtering functionality to a higher order.
- f7ad520 - 🐛 Moves section filtering to higher order
- c830418 - 🚚 Rename ItemGroup → Section
**Issue Number** #172
> [BUG-FIX] Conditional visibility of sections for users

- .github/CHANGELOG.md
- README.md
- docs/authentication.md
- docs/configuring.md
- docs/troubleshooting.md
- package.json
- src/main.js
- src/router.js
- src/utils/Auth.js
- src/utils/ConfigSchema.json
- src/views/Login.vue
- yarn.lock
**Overview**
Adds support for secure authentication using [Keycloak](https://www.keycloak.org/), plus docs
Also refactors the `auth` attribute, which later down the line will involve breaking changes
**Issue Number** #33 
**New Vars** 
Under **`appConfig.auth.keycloak`**
**Field** | **Type** | **Required**| **Description**
--- | --- | --- | ---
**`serverUrl`** | `string` | Required | The URL (or URL/ IP + Port) where your keycloak server is running
**`realm`** | `string` | Required | The name of the realm (must already be created) that you want to use
**`clientId`** | `string` | Required | The Client ID of the client you created for use with Dashy
> [FEATURE] Adds Keycloak support

- package.json
- src/components/LinkItems/ItemIcon.vue
- yarn.lock
**Category**: 
One of: Bugfix
**Overview**
I was having problems with the SimpleIcons applying a color tint because the icons being loaded as SVGs via URL were wrapped in an `object` thus not allowing css styling to apply.
By including the node package for `simple-icons` we can directly access the `SVG` and `PATH` in order to be able to set the `fill` to `currentColor`
**New Vars** _(if applicable)_
Dependency added on `simple-icons:^5.12.0`
**Screenshot** _(if applicable)_
Before:
After:
> Fix simple icons color fill

- src/assets/locales/en.json
- src/components/LinkItems/Item.vue
- src/components/Settings/ConfigLauncher.vue
- src/components/Settings/ThemeSelector.vue
- src/styles/global-styles.scss
**Overview**
Fixes minor issue introduced in previous PR, where the tooltip within the config menu lost it's CSS class, and therefore it's background color, making it pretty much unreadable.
**Issue Number** #205
**Screenshot** 
> [BUG-FIX] Tooltip styling and text

- package.json
- yarn.lock
**Category**: Dependency Update / Security
**Overview**
A security advisory was recently raised in Axios - [`CVE-2021-3749`](https://nvd.nist.gov/vuln/detail/CVE-2021-3749). See [GH Advisory](https://github.com/advisories/GHSA-cph5-m8f7-6c5x).  
This ReDos vuln, was raised and fixed by @ready-research, and resolved in [`5b45711`](https://github.com/axios/axios/commit/5b457116e31db0e88fede6c428e969e87f290929).
This PR just updates Axios to the latest version (`0.21.4`) in order to resolve the issue.
> [SECURITY] Updates Axios, re: CVE-2021-3749

- .github/CHANGELOG.md
- docs/configuring.md
- docs/searching.md
- package.json
- src/components/Settings/SearchBar.vue
- src/utils/ConfigSchema.json
- src/utils/Search.js
- src/utils/defaults.js
- src/views/Home.vue
- src/views/Minimal.vue
[![Lissy93 /FEATURE/multi-search → Lissy93/dashy](https://badgen.net/badge/%23224/Lissy93%20%2FFEATURE%2Fmulti-search%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FEATURE/multi-search) ![Commits: 9 | Files Changed: 10 | Additions: 89](https://badgen.net/badge/New%20Code/Commits%3A%209%20%7C%20Files%20Changed%3A%2010%20%7C%20Additions%3A%2089/dddd00) ![✨ Feature](https://badgen.net/badge/Type/%E2%9C%A8%20Feature/39b0fd) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)
**Overview**
Implements support for multiple search engines …
> [FEATURE] Multi-Search with Custom Bangs

- .github/CHANGELOG.md
- docs/development-guides.md
- docs/release-workflow.md
- netlify.toml
- package.json
- services/serverless-functions/cloud-status-check.js
- services/serverless-functions/not-supported.js
[![Lissy93 /FEATURE/serverless-functions → Lissy93/dashy](https://badgen.net/badge/%23235/Lissy93%20%2FFEATURE%2Fserverless-functions%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FEATURE/serverless-functions) ![Commits: 8 | Files Changed: 7 | Additions: 98](https://badgen.net/badge/New%20Code/Commits%3A%208%20%7C%20Files%20Changed%3A%207%20%7C%20Additions%3A%2098/dddd00) ![✨ Feature](https://badgen.net/badge/Type/%E2%9C%A8%20Feature/39b0fd) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)
**Overview**
Users who deploy via a static …
> [FEATURE] Serverless Functions for CDN Deploys

- .github/CHANGELOG.md
- package.json
- public/index.html
- src/App.vue
- src/components/Configuration/CloudBackupRestore.vue
- src/router.js
- src/utils/CoolConsole.js
- src/utils/ErrorHandler.js
- src/utils/defaults.js
- src/views/Login.vue
[![Lissy93 /FEATURE/improved-loading → Lissy93/dashy](https://badgen.net/badge/%23238/Lissy93%20%2FFEATURE%2Fimproved-loading%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FEATURE/improved-loading) ![Commits: 8 | Files Changed: 10 | Additions: 54](https://badgen.net/badge/New%20Code/Commits%3A%208%20%7C%20Files%20Changed%3A%2010%20%7C%20Additions%3A%2054/dddd00) ![🚚 Refactor](https://badgen.net/badge/Type/%F0%9F%9A%9A%20Refactor/39b0fd) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)
**Overview**
Splash screen is no longer enabled by …
> [FEATURE] Improved Loading

- .github/CHANGELOG.md
- docker/Dockerfile-lite
- docker/nginx.conf
- package.json
**Category**:  Build related changes
**Overview**
Create an Alpine-based container, that serves the built app up with plain NGINX, instead of Node. This is much lighter, but doesn't currently support any of the server-side actions (like status-checks, and writing changes to disk)
> [ARCH] Alpha Version of Dashy-Lite Docker Container

- src/components/InteractiveEditor/EditItem.vue
[![olearycrew](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/olearycrew/f73ae6)](https://github.com/olearycrew) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![olearycrew /344-allow-insecure-type-issue → Lissy93/dashy](https://badgen.net/badge/%23345/olearycrew%20%2F344-allow-insecure-type-issue%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/344-allow-insecure-type-issue) ![Commits: 2 | Files Changed: 1 | Additions: 3](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%203/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
*Thank you for contributing to Dashy! So that your PR can be handled effectively, please populate the following fields (delete sections …
> String to Bool for statusCheckAllowInsecure on save

- src/components/LinkItems/Section.vue
**Category**: Small code update
**Overview**
Previously when items within sections were sorted alphabetically, upper-case titles would appear first. This is a small change to ignore the case when sorting.
**Issue Number** #352
- [] _(If a new config option is added)_ Attribute is outlined in the schema and documented
- [] _(If a new dependency is added)_ Package is essential, and has been checked out for security or performance
> [FEATURE] Case-insensitive item sorting

- .github/CHANGELOG.md
- docs/configuring.md
- docs/widgets.md
- netlify.toml
- package.json
- services/cors-proxy.js
- services/serverless-functions/netlify-cors.js
- src/assets/locales/en.json
- src/components/Widgets/HealthChecks.vue
- src/components/Widgets/NdCpuHistory.vue
- src/components/Widgets/NdLoadHistory.vue
- src/components/Widgets/NdRamHistory.vue
- src/components/Widgets/PiHoleStats.vue
- src/components/Widgets/PiHoleTopQueries.vue
- src/components/Widgets/PiHoleTraffic.vue
- src/components/Widgets/WidgetBase.vue
- src/mixins/WidgetMixin.js
**Category**: Improvement
**Overview**
Some users reporting facing CORS issues with the Pi-Hole widget. This option adds a new option that can be applied to a widget (`useProxy`) that will route the request through the Node proxy server, which contains the right headers.
**Issue Number** #231, #391
**New Vars**
- `useProxy` - boolean, optional
> [FIX] Adds support for proxying CORS requests

- .github/CHANGELOG.md
- package.json
- src/components/LinkItems/Section.vue
- src/utils/SectionHelpers.js
- src/utils/defaults.js
**Category**:   Bugfix
**Overview**
- 2ec5966 🐛 Fixes unable to edit item bug
- #415
- d10e6a8 🐛 Fixes unable to add new app bug
- #390
- ed15816 🐛 Fixes nav links still visible after removing
- #389
**Issue Number** #389 #390 #415 
> [FIX] Minor UI editor fixes

- docs/theming.md
[![icy-comet](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/icy-comet/f73ae6)](https://github.com/icy-comet) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![icy-comet /patch-1 → Lissy93/dashy](https://badgen.net/badge/%23458/icy-comet%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: 
Documentation
**Overview**
The secondary heading caused inconsistent styling on the …
> docs:fix theming title and themes' count

- .github/CHANGELOG.md
- package.json
- src/components/Configuration/JsonEditor.vue
- src/components/InteractiveEditor/EditAppConfig.vue
- src/components/Settings/SettingsContainer.vue
- src/components/Workspace/SideBar.vue
- src/styles/color-themes.scss
- src/utils/ConfigSchema.json
**Category**: UI Bugfix
**Overview**
- 🐛 67326ed - `cutToHeight` was missing from the schema, added it
- 🐛 6b9484a - Removed the full height CSS from colorful theme file
- ⚡️ e472d91 - Improved config validation warnings in JSON editor
- 🩹 d07a5f7 - Removes empty Keycloak block from appConfig editor
- ⚡️ a5944c1 - Adds typechecking to search and clear search for Safari
**Issue Number** #461
> [FIX] Section Height (colourful theme)

- src/components/Widgets/CryptoWatchList.vue
[![rubenandre](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/rubenandre/f73ae6)](https://github.com/rubenandre) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![rubenandre /fix-hardcoded-usd-cryptowatchlist-widget → Lissy93/dashy](https://badgen.net/badge/%23467/rubenandre%20%2Ffix-hardcoded-usd-cryptowatchlist-widget%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix-hardcoded-usd-cryptowatchlist-widget) ![Commits: 1 | Files Changed: 1 | Additions: 1](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%201/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
*Thank …
> 🐛 Fix hardcoded usd currency

- Dockerfile
[![Singebob](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/Singebob/f73ae6)](https://github.com/Singebob) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![Singebob /master → Lissy93/dashy](https://badgen.net/badge/%23495/Singebob%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 2 | Files Changed: 1 | Additions: 16](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%2016/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: Bugix
> One of: Bugfix / Feature / …
> Add group and user in dockerfile to run container as unprivileged

- Dockerfile
Reverts: #495
Reopens: #340 
Due to: #498
Fixes: #499
> [REVERRT] Add group and user in dockerfile to run container as unprivileged

- src/views/Home.vue
[![Ateroz](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/Ateroz/f73ae6)](https://github.com/Ateroz) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![Ateroz /fix-ui-add-new-section-when-no-sections → Lissy93/dashy](https://badgen.net/badge/%23536/Ateroz%20%2Ffix-ui-add-new-section-when-no-sections%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix-ui-add-new-section-when-no-sections) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
*Thank you for contributing to …
> :bug: Show Add New Section when no sections exist

- .github/CHANGELOG.md
- .github/LATEST_CHANGELOG.md
- Dockerfile
- package.json
- src/utils/ConfigAccumalator.js
[![Ateroz](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/Ateroz/f73ae6)](https://github.com/Ateroz) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![Ateroz /fix-several-issues-with-conf-not-loaded → Lissy93/dashy](https://badgen.net/badge/%23559/Ateroz%20%2Ffix-several-issues-with-conf-not-loaded%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix-several-issues-with-conf-not-loaded) ![Commits: 3 | Files Changed: 5 | Additions: 19](https://badgen.net/badge/New%20Code/Commits%3A%203%20%7C%20Files%20Changed%3A%205%20%7C%20Additions%3A%2019/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
*Thank you for contributing to Dashy! So that your PR can be handled effectively, please populate the following fields …
> Fix several issues with conf not loaded

- docs/deployment.md
[![StevKast](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/StevKast/f73ae6)](https://github.com/StevKast) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![StevKast /master → Lissy93/dashy](https://badgen.net/badge/%23565/StevKast%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**:  Documentation
**Overview**
The container root folder is not needed when specifying a volume. It …
> [FIX] Fixing docker-compose example volume path

- src/components/Settings/SearchBar.vue
[![moemoeq](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/moemoeq/f73ae6)](https://github.com/moemoeq) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![moemoeq /FIX/611_keep-all-word-break-for-cjk → Lissy93/dashy](https://badgen.net/badge/%23612/moemoeq%20%2FFIX%2F611_keep-all-word-break-for-cjk%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FIX/611_keep-all-word-break-for-cjk) ![Commits: 1 | Files Changed: 1 | Additions: 1](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%201/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
*Thank you for contributing to …
> [FIX] Prevent line breaks in search-label when using CJK languages

- docs/widgets.md
- src/components/Widgets/StatPing.vue
[![marekful](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/marekful/f73ae6)](https://github.com/marekful) ![✨ Feature](https://badgen.net/badge/Type/%E2%9C%A8%20Feature/39b0fd) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![marekful /FEATURE/StatPing-widget-group-filter-and-compact-view → Lissy93/dashy](https://badgen.net/badge/%23714/marekful%20%2FFEATURE%2FStatPing-widget-group-filter-and-compact-view%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FEATURE/StatPing-widget-group-filter-and-compact-view) ![Commits: 1 | Files Changed: 2 | Additions: 43](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%2043/dddd00) ![Unchecked …
> :sparkles: Optionally allow StatPing widget to filter on group

- src/components/Widgets/Apod.vue
- src/utils/defaults.js
[![k073l](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/k073l/f73ae6)](https://github.com/k073l) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![k073l /FEATURE/735_apod_update → Lissy93/dashy](https://badgen.net/badge/%23745/k073l%20%2FFEATURE%2F735_apod_update%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FEATURE/735_apod_update) ![Commits: 2 | Files Changed: 2 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: 
> Bugfix/Feature
**Overview**
> Changes APOD API URL to https://go-apod.herokuapp.com/apod from [Lissy93/go-apod](https://github.com/Lissy93/go-apod) and fixes …
> Replace APOD API with new one

- src/store.js
- src/utils/defaults.js
[![marekful](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/marekful/f73ae6)](https://github.com/marekful) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![marekful /FEATURE/page-theme-override → Lissy93/dashy](https://badgen.net/badge/%23752/marekful%20%2FFEATURE%2Fpage-theme-override%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FEATURE/page-theme-override) ![Commits: 1 | Files Changed: 2 | Additions: 16](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%2016/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
**Category**: 
> One of: Feature
**Overview**
> …
> :sparkles: Allow pages to override theme

- src/components/Widgets/WidgetBase.vue
[![patrickheeney](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/patrickheeney/f73ae6)](https://github.com/patrickheeney) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![patrickheeney /FEATURE/Improve-Widget-Base → Lissy93/dashy](https://badgen.net/badge/%23758/patrickheeney%20%2FFEATURE%2FImprove-Widget-Base%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FEATURE/Improve-Widget-Base) ![Commits: 1 | Files Changed: 1 | Additions: -439](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%20-439/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: Refactoring Only
**Overview**
My hope is to support specifying a custom widget type after mounting it …
> :sparkles: Remove component repetition

- services/ssl-server.js
[![marekful](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/marekful/f73ae6)](https://github.com/marekful) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![marekful /FIX/start-ssl-on-slow-filesystem → Lissy93/dashy](https://badgen.net/badge/%23760/marekful%20%2FFIX%2Fstart-ssl-on-slow-filesystem%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FIX/start-ssl-on-slow-filesystem) ![Commits: 1 | Files Changed: 1 | Additions: 2](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%202/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
**Category**: 
> Bugfix
**Overview** …
> :adhesive_bandage: Ensure stat finished before startSSLServer()

- src/components/LinkItems/Item.vue
- src/mixins/ItemMixin.js
[![marekful](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/marekful/f73ae6)](https://github.com/marekful) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![marekful /FIX/stop-status-checks → Lissy93/dashy](https://badgen.net/badge/%23767/marekful%20%2FFIX%2Fstop-status-checks%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FIX/stop-status-checks) ![Commits: 1 | Files Changed: 2 | Additions: 5](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%205/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
**Category**: 
Bugfix
**Overview**
Status-checks keep running when …
> :adhesive_bandage: Stop status-check when Item is destroyed

- src/components/Widgets/GlDiskSpace.vue
[![BRAVO68WEB](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/BRAVO68WEB/f73ae6)](https://github.com/BRAVO68WEB) ![🐛 Fix](https://badgen.net/badge/Type/%F0%9F%90%9B%20Fix/39b0fd) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![BRAVO68WEB /fix/disk-calc → Lissy93/dashy](https://badgen.net/badge/%23788/BRAVO68WEB%20%2Ffix%2Fdisk-calc%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix/disk-calc) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
**Category**: 
> One of: Bugfix
**Overview**
>  It should be 'Used' instead of 'Free'. Its …
> Fix storage calculation

- docs/widgets.md
- src/components/Widgets/PublicHolidays.vue
[![cauterize](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/cauterize/f73ae6)](https://github.com/cauterize) ![✨ Feature](https://badgen.net/badge/Type/%E2%9C%A8%20Feature/39b0fd) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![cauterize /feat/public_holidays_widget_state_parameter → Lissy93/dashy](https://badgen.net/badge/%23875/cauterize%20%2Ffeat%2Fpublic_holidays_widget_state_parameter%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/feat/public_holidays_widget_state_parameter) ![Commits: 3 | Files Changed: 2 | Additions: 9](https://badgen.net/badge/New%20Code/Commits%3A%203%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%209/dddd00)
*Thank you for contributing to Dashy! So that your PR can be handled effectively, please populate …
> :sparkles: Adds state option for PublicHolidays widget

- Dockerfile
[![sur1v](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/sur1v/f73ae6)](https://github.com/sur1v) ![🏗️ Architecture](https://badgen.net/badge/Type/%F0%9F%8F%97%EF%B8%8F%20Architecture/39b0fd) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![sur1v /master → Lissy93/dashy](https://badgen.net/badge/%23891/sur1v%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: -1](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%20-1/dddd00)
**Category**: 
Build related changes …
> Removed build watch and tini from container run-time

- docs/authentication.md
- docs/configuring.md
- package.json
- src/store.js
- src/utils/ConfigSchema.json
[![Cereal916](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/Cereal916/f73ae6)](https://github.com/Cereal916) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![Cereal916 /disableConfigurationForNonAdmin → Lissy93/dashy](https://badgen.net/badge/%23900/Cereal916%20%2FdisableConfigurationForNonAdmin%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/disableConfigurationForNonAdmin) ![Commits: 3 | Files Changed: 4 | Additions: 8](https://badgen.net/badge/New%20Code/Commits%3A%203%20%7C%20Files%20Changed%3A%204%20%7C%20Additions%3A%208/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: 
>  Feature 
**Overview**
> Provides an option to allow admin functionality while still hiding local auth …
> Add config option to disable all UI config features for non admin users.

- src/components/LinkItems/Section.vue
[![DawidPietrykowski](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/DawidPietrykowski/f73ae6)](https://github.com/DawidPietrykowski) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![DawidPietrykowski /FIX/950_widget-width → Lissy93/dashy](https://badgen.net/badge/%23955/DawidPietrykowski%20%2FFIX%2F950_widget-width%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FIX/950_widget-width) ![Commits: 1 | Files Changed: 1 | Additions: 2](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%202/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) …
> Added css width declaration for other browsers

- src/components/LinkItems/ItemIcon.vue
[![dkyeremeh](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/dkyeremeh/f73ae6)](https://github.com/dkyeremeh) ![🐛 Fix](https://badgen.net/badge/Type/%F0%9F%90%9B%20Fix/39b0fd) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![dkyeremeh /subdomain-favicon → Lissy93/dashy](https://badgen.net/badge/%23926/dkyeremeh%20%2Fsubdomain-favicon%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/subdomain-favicon) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
*Thank you for contributing to Dashy! So that your PR can be handled effectively, please …
> Allow favicons for subdomains

- docs/widgets.md
- src/components/Widgets/Clock.vue
[![Totto16](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/Totto16/f73ae6)](https://github.com/Totto16) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![Totto16 /master → Lissy93/dashy](https://badgen.net/badge/%23982/Totto16%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 4 | Files Changed: 2 | Additions: 2](https://badgen.net/badge/New%20Code/Commits%3A%204%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%202/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: 
> Bugfix / Improvement
**Overview**
> 
**config: use12Hour** | **Expected behavior** | **Previous Behavior is correct** | **PR Behavior is correct**
--- | ---  | --- | --- 
unset | default to the …
> - Clock Widget: fix bug, better default Handling for:  use12Hour, showSeconds

- src/assets/locales/en.json
- src/assets/locales/fr.json
- src/views/Login.vue
[![Dylan-Bs](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/Dylan-Bs/f73ae6)](https://github.com/Dylan-Bs) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![Dylan-Bs /master → Lissy93/dashy](https://badgen.net/badge/%231029/Dylan-Bs%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 3 | Additions: 15](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%203%20%7C%20Additions%3A%2015/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**:  Code style update 
**Overview**
Improving Internationalization process. Adding guest variables in locales "en" and "fr" 
Feel free to correct me, …
> :globe_with_meridians: Adding Guest translations

- docs/widgets.md
- src/components/Widgets/HealthChecks.vue
[![m42e](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/m42e/f73ae6)](https://github.com/m42e) ![🚚 Refactor](https://badgen.net/badge/Type/%F0%9F%9A%9A%20Refactor/39b0fd) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) ![✅ Ready](https://badgen.net/badge/Status/%E2%9C%85%20Ready/3ef963) [![m42e /multiple-healthcheck-keys → Lissy93/dashy](https://badgen.net/badge/%231039/m42e%20%2Fmultiple-healthcheck-keys%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/multiple-healthcheck-keys) ![Commits: 1 | Files Changed: 2 | Additions: 43](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%2043/dddd00) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) …
> Allow multiple Project Keys for HealthChecks

- src/components/Widgets/XkcdComic.vue
[![m42e](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/m42e/f73ae6)](https://github.com/m42e) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![m42e /xkcd-show-alt → Lissy93/dashy](https://badgen.net/badge/%231043/m42e%20%2Fxkcd-show-alt%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/xkcd-show-alt) ![Commits: 1 | Files Changed: 1 | Additions: 11](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%2011/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: Bufix
**Overview**
The alt text …
> XKCD: Use tooltip for alt text

- docs/widgets.md
- src/components/Widgets/PiHoleStats.vue
- src/components/Widgets/PiHoleTraffic.vue
[![albcp](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/albcp/f73ae6)](https://github.com/albcp) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![albcp /master → Lissy93/dashy](https://badgen.net/badge/%231074/albcp%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 2 | Files Changed: 3 | Additions: 18](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%203%20%7C%20Additions%3A%2018/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
**Overview**
- Added authentication to PiHoleStats and PiHoleTraffic widgets as required since Pi-hole Web …
> Fixed Pi-Hole widgets adding authentication

- Dockerfile
- services/healthcheck.js
[![rtm516](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/rtm516/f73ae6)](https://github.com/rtm516) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![rtm516 /master → Lissy93/dashy](https://badgen.net/badge/%231076/rtm516%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 2 | Files Changed: 2 | Additions: 7](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%207/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: Bugfix and Feature
**Overview**
Fixes health-check issues when using SSL or a slower server that takes more than 2s to check
> Fix health-check when using SSL

- docs/widgets.md
- src/components/Widgets/CveVulnerabilities.vue
[![albcp](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/albcp/f73ae6)](https://github.com/albcp) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![albcp /master → Lissy93/dashy](https://badgen.net/badge/%231075/albcp%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 2 | Files Changed: 2 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
**Category**: Bugfix and Documentation
**Overview**
The *cve-vulnerabilities* widget has been updated to include a filter by …
> Fixed filtering by productId in cve-vulnerabilities widget

- docs/widgets.md
- src/components/Widgets/DroneCi.vue
- src/components/Widgets/DroneIo.vue
- src/components/Widgets/WidgetBase.vue
[![m42e](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/m42e/f73ae6)](https://github.com/m42e) ![✨ Feature](https://badgen.net/badge/Type/%E2%9C%A8%20Feature/39b0fd) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![m42e /drone-io-widget → Lissy93/dashy](https://badgen.net/badge/%231037/m42e%20%2Fdrone-io-widget%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/drone-io-widget) ![Commits: 9 | Files Changed: 3 | Additions: 276](https://badgen.net/badge/New%20Code/Commits%3A%209%20%7C%20Files%20Changed%3A%203%20%7C%20Additions%3A%20276/dddd00) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
*Thank you for contributing to Dashy! So that your PR can be handled effectively, please populate the …
> Drone io widget

- docs/widgets.md
- src/components/Widgets/Mvg.vue
- src/components/Widgets/MvgConnection.vue
- src/components/Widgets/WidgetBase.vue
- src/utils/defaults.js
[![m42e](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/m42e/f73ae6)](https://github.com/m42e) ![✨ Feature](https://badgen.net/badge/Type/%E2%9C%A8%20Feature/39b0fd) ![Large](https://badgen.net/badge/PR%20Size/Large/f4b546) [![m42e /mvg-upstream → Lissy93/dashy](https://badgen.net/badge/%231047/m42e%20%2Fmvg-upstream%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/mvg-upstream) ![Commits: 5 | Files Changed: 5 | Additions: 816](https://badgen.net/badge/New%20Code/Commits%3A%205%20%7C%20Files%20Changed%3A%205%20%7C%20Additions%3A%20816/dddd00) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
Display mvg departure times for MVG station.
**Overview**
Display The departure times of the next …
> Added Mvg Widget

- src/components/Widgets/HealthChecks.vue
[![m42e](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/m42e/f73ae6)](https://github.com/m42e) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![m42e /healthcheck-fix-errors → Lissy93/dashy](https://badgen.net/badge/%231048/m42e%20%2Fhealthcheck-fix-errors%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/healthcheck-fix-errors) ![Commits: 1 | Files Changed: 1 | Additions: 1](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%201/dddd00) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) ![🚫 Merge Conflicts](https://badgen.net/badge/Warning/%F0%9F%9A%AB%20Merge%20Conflicts/f25265)
**Overview**
Fixed linter errors introduces with …
> Fix HealthChecks linting errors

- public/manifest.json
[![kieraneglin](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/kieraneglin/f73ae6)](https://github.com/kieraneglin) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![kieraneglin /FIX/add-to-homescreen-404 → Lissy93/dashy](https://badgen.net/badge/%231026/kieraneglin%20%2FFIX%2Fadd-to-homescreen-404%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FIX/add-to-homescreen-404) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: 
> Bugfix
**Overview**
> The "add to homescreen" functionality on Android is broken. When adding your dashboard to your …
> 🐛 Update manifest.json's start_url to bare root path

- .github/workflows/generate-credits.yml
[![a-mnich](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/a-mnich/f73ae6)](https://github.com/a-mnich) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![a-mnich /FIX/Authors → Lissy93/dashy](https://badgen.net/badge/%231091/a-mnich%20%2FFIX%2FAuthors%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FIX/Authors) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: Bugfix 
**Overview**
The Github Action version of __wow-actions/update-authors__ which is used for generating the [AUTHORS file](https://github.com/Lissy93/dashy/blob/master/.github/AUTHOR …
> :construction_worker: bump version:  update-authors GitHub action

- src/components/Workspace/SideBar.vue
[![itsmejoeeey](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/itsmejoeeey/f73ae6)](https://github.com/itsmejoeeey) ![🐛 Fix](https://badgen.net/badge/Type/%F0%9F%90%9B%20Fix/39b0fd) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![itsmejoeeey /BUG/1024_Workspace-trailing-slash → Lissy93/dashy](https://badgen.net/badge/%231066/itsmejoeeey%20%2FBUG%2F1024_Workspace-trailing-slash%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/BUG/1024_Workspace-trailing-slash) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00)
* Add trailing slash to switch-view-buttons on Workspace sidebar. This prevents a bug when later using switch view buttons …
> :bug: Add trailing slash to quick fix #1064

- docs/authentication.md
- package.json
- src/utils/ConfigSchema.json
- src/utils/KeycloakAuth.js
[![marekful](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/marekful/f73ae6)](https://github.com/marekful) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![marekful /FEATURE/pass-idp-hint-to-keycloak-auth → Lissy93/dashy](https://badgen.net/badge/%231101/marekful%20%2FFEATURE%2Fpass-idp-hint-to-keycloak-auth%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FEATURE/pass-idp-hint-to-keycloak-auth) ![Commits: 3 | Files Changed: 4 | Additions: 7](https://badgen.net/badge/New%20Code/Commits%3A%203%20%7C%20Files%20Changed%3A%204%20%7C%20Additions%3A%207/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
**Category**: …
> [FEATURE/IMPROVEMENT] Pass 'IdP Hint' to Keycloak

- server.js
[![itsmejoeeey](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/itsmejoeeey/f73ae6)](https://github.com/itsmejoeeey) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![itsmejoeeey /BUG/1067_Server-fallback-serve-index → Lissy93/dashy](https://badgen.net/badge/%231068/itsmejoeeey%20%2FBUG%2F1067_Server-fallback-serve-index%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/BUG/1067_Server-fallback-serve-index) ![Commits: 1 | Files Changed: 1 | Additions: 2](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%202/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
*Thank you for contributing to Dashy! So that your PR can be handled effectively, please populate the …
> :bug: Serve index.html as fallback to fix #1067

- src/assets/locales/en.json
- src/assets/locales/fr.json
- src/components/Configuration/AppInfoModal.vue
- src/components/Configuration/CloudBackupRestore.vue
- src/components/Configuration/ConfigContainer.vue
- src/components/Configuration/CustomCss.vue
- src/components/PageStrcture/Footer.vue
- src/components/PageStrcture/LoadingScreen.vue
[![DimitriDR](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/DimitriDR/f73ae6)](https://github.com/DimitriDR) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![DimitriDR /master → Lissy93/dashy](https://badgen.net/badge/%231041/DimitriDR%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 4 | Files Changed: 8 | Additions: 120](https://badgen.net/badge/New%20Code/Commits%3A%204%20%7C%20Files%20Changed%3A%208%20%7C%20Additions%3A%20120/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
**Category**: 
> One of: Feature / Translation
**Overview**
> I've seen that some elements are not …
> Increasing localization for every element on Dashy

- src/components/Widgets/Clock.vue
- src/components/Widgets/Mvg.vue
- src/mixins/ItemMixin.js
**Overview**
- 🐛 4fc3abf5110f92508ab6d23ca8cc66b5f0dc29ca - Fix most-used and last-used counter
- The issue was caused by item ID being undefined, as `this.id` should have been `this.item.id`
- 🚨 c3749c68370a94eb8033df8b225b6e516a99bd9c - Fix lint warning in clock component (use single quotes)
- 🚨 743232e59741e4837aa33c7f27204254592267ca - Fix lint warning in Mvg widget (use 2-space indentation)
**Issue Number** #1056 #1033
- [] _(If a new config option is added)_ Attribute is outlined in the schema and documented
- [] _(If a new dependency is added)_ Package is essential, and has been checked out for security or performance
> [FIX] Counter for most-used + last-used, and lint warns

- docs/widgets.md
- src/components/Widgets/Linkding.vue
- src/components/Widgets/WidgetBase.vue
[![m42e](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/m42e/f73ae6)](https://github.com/m42e) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![m42e /linkding → Lissy93/dashy](https://badgen.net/badge/%231106/m42e%20%2Flinkding%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/linkding) ![Commits: 2 | Files Changed: 3 | Additions: 138](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%203%20%7C%20Additions%3A%20138/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
*Thank you for contributing to Dashy! So that your PR can be handled effectively, please populate the following fields (delete …
> Added linkding widget

- src/components/Widgets/GlCpuTemp.vue
[![luispabon](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/luispabon/f73ae6)](https://github.com/luispabon) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![luispabon /sensors → Lissy93/dashy](https://badgen.net/badge/%231157/luispabon%20%2Fsensors%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/sensors) ![Commits: 1 | Files Changed: 1 | Additions: 42](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%2042/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …
> Tweak GlCpuTemp widget to support other sensor units

- docs/widgets.md
- package.json
- src/components/Widgets/RssFeed.vue
- yarn.lock
[![hockeymikey](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/hockeymikey/f73ae6)](https://github.com/hockeymikey) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![hockeymikey /master → Lissy93/dashy](https://badgen.net/badge/%231167/hockeymikey%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 3 | Files Changed: 4 | Additions: 51](https://badgen.net/badge/New%20Code/Commits%3A%203%20%7C%20Files%20Changed%3A%204%20%7C%20Additions%3A%2051/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm …
> Add in rss parsing library and option to use it instead of the API

- src/styles/weather-icons.scss
[![gbrown09](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/gbrown09/f73ae6)](https://github.com/gbrown09) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![gbrown09 /weather-icon-fix → Lissy93/dashy](https://badgen.net/badge/%231175/gbrown09%20%2Fweather-icon-fix%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/weather-icon-fix) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …
> Swapping incorrect icons

- src/utils/Search.js
[![ssrangisetti](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/ssrangisetti/f73ae6)](https://github.com/ssrangisetti) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![ssrangisetti /patch-1 → Lissy93/dashy](https://badgen.net/badge/%231171/ssrangisetti%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 2 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …
> Add support searching multiple words.

- docs/widgets.md
- src/components/Widgets/GlCpuTemp.vue
- src/utils/MiscHelpers.js
[![altearius](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/altearius/f73ae6)](https://github.com/altearius) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![altearius /FEATURE/cpu-temp-units → Lissy93/dashy](https://badgen.net/badge/%231182/altearius%20%2FFEATURE%2Fcpu-temp-units%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FEATURE/cpu-temp-units) ![Commits: 1 | Files Changed: 3 | Additions: 47](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%203%20%7C%20Additions%3A%2047/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …
> ✨ Permit users to choose Celsius or Fahrenheit.

- package.json
[![baifengheixi](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/baifengheixi/f73ae6)](https://github.com/baifengheixi) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![baifengheixi /master → Lissy93/dashy](https://badgen.net/badge/%231178/baifengheixi%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)
**Category**: …
> 🔧 Set range of node version in package.json

- docs/widgets.md
- src/components/Widgets/Proxmox.vue
- src/components/Widgets/WidgetBase.vue
[![alayham](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/alayham/f73ae6)](https://github.com/alayham) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![alayham /proxmox-lists → Lissy93/dashy](https://badgen.net/badge/%231210/alayham%20%2Fproxmox-lists%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/proxmox-lists) ![Commits: 1 | Files Changed: 3 | Additions: 216](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%203%20%7C%20Additions%3A%20216/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/? …
> initial commit of the proxmox lists widget

- docs/widgets.md
- src/components/Widgets/CustomSearch.vue
- src/components/Widgets/WidgetBase.vue
[![alayham](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/alayham/f73ae6)](https://github.com/alayham) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![alayham /custom-search → Lissy93/dashy](https://badgen.net/badge/%231212/alayham%20%2Fcustom-search%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/custom-search) ![Commits: 1 | Files Changed: 3 | Additions: 126](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%203%20%7C%20Additions%3A%20126/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/? …
> initial commit of the custom search widget

- src/utils/MiscHelpers.js
[![altearius](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/altearius/f73ae6)](https://github.com/altearius) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![altearius /FEATURE/temporal-plurality → Lissy93/dashy](https://badgen.net/badge/%231217/altearius%20%2FFEATURE%2Ftemporal-plurality%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FEATURE/temporal-plurality) ![Commits: 3 | Files Changed: 1 | Additions: 15](https://badgen.net/badge/New%20Code/Commits%3A%203%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%2015/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request …
> 🩹 Singular/plural forms for time counts.

- docs/development-guides.md
[![altearius](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/altearius/f73ae6)](https://github.com/altearius) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![altearius /FEATURE/documentation → Lissy93/dashy](https://badgen.net/badge/%231216/altearius%20%2FFEATURE%2Fdocumentation%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FEATURE/documentation) ![Commits: 1 | Files Changed: 1 | Additions: -18](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%20-18/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …
> 📝 How to register a widget.

- public/index.html
**Category**: 
Fix/ update
**Overview**
Imports the PWA manifest into index.html, some newer browsers don't automatically pick it up
**Issue Number**  #1215
> [FEATURE] Import manifest in index.html

- docs/widgets.md
[![ethan-hann](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/ethan-hann/f73ae6)](https://github.com/ethan-hann) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![ethan-hann /patch-1 → Lissy93/dashy](https://badgen.net/badge/%231248/ethan-hann%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_mediu …
> Fixed link and grammar mistake

- docs/widgets.md
- src/components/Widgets/PublicHolidays.vue
[![BhasherBEL](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/BhasherBEL/f73ae6)](https://github.com/BhasherBEL) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![BhasherBEL /master → Lissy93/dashy](https://badgen.net/badge/%231192/BhasherBEL%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 2 | Additions: 2](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%202/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=g …
> Add lang option for public holidays

- docs/alternate-views.md
- docs/development-guides.md
[![wozboz](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/wozboz/f73ae6)](https://github.com/wozboz) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![wozboz /master → Lissy93/dashy](https://badgen.net/badge/%231293/wozboz%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 2 | Files Changed: 2 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lis …
> Fixed typos in documentation

- .env
- docs/developing.md
- services/save-config.js
[![rokiden](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/rokiden/f73ae6)](https://github.com/rokiden) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![rokiden /master → Lissy93/dashy](https://badgen.net/badge/%231326/rokiden%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 3 | Additions: 6](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%203%20%7C%20Additions%3A%206/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d …
> Added BACKUP_DIR env for conf.yml backups

- src/styles/color-themes.scss
- src/utils/defaults.js
[![kt-alt](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/kt-alt/f73ae6)](https://github.com/kt-alt) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![kt-alt /theme/add-tama-theme → Lissy93/dashy](https://badgen.net/badge/%231347/kt-alt%20%2Ftheme%2Fadd-tama-theme%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/theme/add-tama-theme) ![Commits: 1 | Files Changed: 2 | Additions: 81](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%2081/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …
> add tama theme

- src/components/LinkItems/Section.vue
[![ThinkSalat](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/ThinkSalat/f73ae6)](https://github.com/ThinkSalat) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![ThinkSalat /bug/1274-popup-modal-fix → Lissy93/dashy](https://badgen.net/badge/%231275/ThinkSalat%20%2Fbug%2F1274-popup-modal-fix%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/bug/1274-popup-modal-fix) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=L …
> bug #1274 multi page popup modal fix

- services/healthcheck.js
[![stavros-k](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/stavros-k/f73ae6)](https://github.com/stavros-k) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![stavros-k /patch-1 → Lissy93/dashy](https://badgen.net/badge/%231384/stavros-k%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …
> Fix healthcheck.js without ssl

- docs/icons.md
- src/utils/defaults.js
[![bubylou](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/bubylou/f73ae6)](https://github.com/bubylou) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![bubylou /master → Lissy93/dashy](https://badgen.net/badge/%231344/bubylou%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 2 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_sourc …
> Update generative icon API

- docs/authentication.md
- docs/configuring.md
- server.js
- services/config-validator.js
- services/get-user.js
- src/main.js
- src/utils/ConfigSchema.json
- src/utils/HeaderAuth.js
- src/utils/defaults.js
[![toddejohnson](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/toddejohnson/f73ae6)](https://github.com/toddejohnson) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![toddejohnson /REFACTOR/2.1.2_unified-config → Lissy93/dashy](https://badgen.net/badge/%231390/toddejohnson%20%2FREFACTOR%2F2.1.2_unified-config%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/REFACTOR/2.1.2_unified-config) ![Commits: 4 | Files Changed: 9 | Additions: 214](https://badgen.net/badge/New%20Code/Commits%3A%204%20%7C%20Files%20Changed%3A%209%20%7C%20Additions%3A%20214/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" …
> Attempt at adding header auth. Ignore Settings #981

- docs/authentication.md
- src/components/InteractiveEditor/EditMultiPages.vue
- src/components/PageStrcture/Nav.vue
- src/utils/CheckPageVisibility.js
- src/utils/ConfigSchema.json
[![mmihaly](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/mmihaly/f73ae6)](https://github.com/mmihaly) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![mmihaly /page-visibility-configuration → Lissy93/dashy](https://badgen.net/badge/%231420/mmihaly%20%2Fpage-visibility-configuration%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/page-visibility-configuration) ![Commits: 2 | Files Changed: 5 | Additions: 142](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%205%20%7C%20Additions%3A%20142/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request …
> Page visibility configuration

- README.md
- docs/deployment.md
[![FraglyG](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/FraglyG/f73ae6)](https://github.com/FraglyG) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![FraglyG /master → Lissy93/dashy](https://badgen.net/badge/%231462/FraglyG%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 2 | Additions: 12](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%2012/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/1112165 …
> Add Railway as a deployment method

- docs/widgets.md
- src/components/Widgets/Proxmox.vue
[![alayham](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/alayham/f73ae6)](https://github.com/alayham) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![alayham /fix-proxmox-widger-sorting → Lissy93/dashy](https://badgen.net/badge/%231460/alayham%20%2Ffix-proxmox-widger-sorting%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix-proxmox-widger-sorting) ![Commits: 2 | Files Changed: 2 | Additions: 5](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%205/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png" …
> Fixed sorting by vmid in the proxmox widget

- docs/deployment.md
- docs/troubleshooting.md
[![CrazyWolf13](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/CrazyWolf13/f73ae6)](https://github.com/CrazyWolf13) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![CrazyWolf13 /master → Lissy93/dashy](https://badgen.net/badge/%231474/CrazyWolf13%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 4 | Files Changed: 2 | Additions: 22](https://badgen.net/badge/New%20Code/Commits%3A%204%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%2022/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …
> [Docs] Config not saving troubleshooting

- .github/workflows/docker-build-publish.yml
- .npmrc
- Dockerfile
- netlify.toml
- package.json
**Overview**
After version 2.1.2 was released, which included a major update on many dependencies, plus upgrading the version of Node used, the [`docker-build-publish.yml`](https://github.com/Lissy93/dashy/blob/master/.github/workflows/docker-build-publish.yml) workflow started failing. This was narrowed down to be caused by it hanging when it got to the ARM/v7 architecture build, and as such that was temporarily removed so that build would succeed. 
This PR adds back ARM/v7 support, while keeping all other architectures working.
More details here: https://github.com/docker/build-push-action/issues/1071#issuecomment-1976574780
Not a screenshot, but see workflow run: …
> [FIX] 🐳 Adds back Docker arm/v7 support

- docs/widgets.md
- src/components/Widgets/UptimeKuma.vue
- src/components/Widgets/WidgetBase.vue
[![imjimmeh](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/imjimmeh/f73ae6)](https://github.com/imjimmeh) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![imjimmeh /feat/uptime-kuma-widget → Lissy93/dashy](https://badgen.net/badge/%231501/imjimmeh%20%2Ffeat%2Fuptime-kuma-widget%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/feat/uptime-kuma-widget) ![Commits: 10 | Files Changed: 3 | Additions: 292](https://badgen.net/badge/New%20Code/Commits%3A%2010%20%7C%20Files%20Changed%3A%203%20%7C%20Additions%3A%20292/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …
> feat(widgets): :sparkles: Add Uptime Kuma Widget

- package.json
This is a draft, experimenting with going back to the Vue CLI to handle the rebuilding.
Previously this approach introduced a bug which caused a rebuild loop, which was why the new `watch-for-changes` function was written, but that function is memory intensive. But there have been some architectural changes since, so I'm giving this a second shot.
This will not be merged until I can verify 100% that it does not re-introduce the old infinite rebuild loop bug. 
**Overview**
> Briefly outline your new changes...
**Issue Number**  #1500
**New Vars**  N/A
> [FIX] Memory issue (WIP)

- src/mixins/WidgetMixin.js
I made a change in v3 which removed the use of axios. This broke header auth for widgets, so this PR just reverts that change, putting axios back in and (hopefully 🤞) fixing the bug. 
**Overview**
> Briefly outline your new changes...
**Issue Number** #1549
**Screenshot** _N/A
> [FIX] Auth headers for widgets

- src/components/Widgets/PublicHolidays.vue
**Overview**
Safari being "special". Doesn't accept dates which don't include a time.
PR just adds a time (midnight) onto the dates returned by the API.
**Issue Number**  #1532
> [FIX] Date parsing on Safari for the Public Holidays widget

- docs/authentication.md
- docs/configuring.md
- package.json
- src/components/Settings/AuthButtons.vue
- src/main.js
- src/utils/Auth.js
- src/utils/ConfigSchema.json
- src/utils/OidcAuth.js
- src/utils/defaults.js
[![twsouthwick](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/twsouthwick/f73ae6)](https://github.com/twsouthwick) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![twsouthwick /oidc → Lissy93/dashy](https://badgen.net/badge/%231573/twsouthwick%20%2Foidc%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/oidc) ![Commits: 1 | Files Changed: 9 | Additions: 196](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%209%20%7C%20Additions%3A%20196/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_med …
> Enable public application OIDC client support

- src/components/Widgets/GitHubTrending.vue
- src/utils/defaults.js
[![alhazmy13](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/alhazmy13/f73ae6)](https://github.com/alhazmy13) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![alhazmy13 /master → Lissy93/dashy](https://badgen.net/badge/%231562/alhazmy13%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 5 | Files Changed: 2 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%205%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216 …
> Update Github trending widget

- src/directives/LongPress.js
[![ddenev](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/ddenev/f73ae6)](https://github.com/ddenev) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![ddenev /master → Lissy93/dashy](https://badgen.net/badge/%231623/ddenev%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 6](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%206/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85 …
> [Fix] Scolling on mobile brings up menu #1261

- docs/widgets.md
- services/cors-proxy.js
- src/components/Widgets/TacticalRMM.vue
- src/components/Widgets/WidgetBase.vue
[![conlan0](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/conlan0/f73ae6)](https://github.com/conlan0) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![conlan0 /master → Lissy93/dashy](https://badgen.net/badge/%231649/conlan0%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 4 | Files Changed: 4 | Additions: 264](https://badgen.net/badge/New%20Code/Commits%3A%204%20%7C%20Files%20Changed%3A%204%20%7C%20Additions%3A%20264/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524- …
> ✨ Tactical RMM Widget

- docs/authentication.md
- docs/configuring.md
- src/utils/ConfigSchema.json
- src/utils/OidcAuth.js
[![nOw-Ay](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/nOw-Ay/f73ae6)](https://github.com/nOw-Ay) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![nOw-Ay /master → Lissy93/dashy](https://badgen.net/badge/%231641/nOw-Ay%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 4 | Additions: 8](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%204%20%7C%20Additions%3A%208/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=L …
>  🔧 add OIDC scope option

- services/rebuild-app.js
- tsconfig.json
- vue.config.js
[![webysther](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/webysther/f73ae6)](https://github.com/webysther) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![webysther /master → Lissy93/dashy](https://badgen.net/badge/%231836/webysther%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 3 | Files Changed: 3 | Additions: 5](https://badgen.net/badge/New%20Code/Commits%3A%203%20%7C%20Files%20Changed%3A%203%20%7C%20Additions%3A%205/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github …
> Memory usage improvements

- src/App.vue
- src/mixins/ThemingMixin.js
[![vishwamartur](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/vishwamartur/f73ae6)](https://github.com/vishwamartur) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![vishwamartur /add-auto-theme-switch → Lissy93/dashy](https://badgen.net/badge/%231770/vishwamartur%20%2Fadd-auto-theme-switch%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/add-auto-theme-switch) ![Commits: 1 | Files Changed: 2 | Additions: 18](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%2018/dddd00) ![Category](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Category/f25265) ![Overview](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Overview/f25265) ![Quality …
> Add auto dark/light theme switch based on OS preference

- README.md
- docs/configuring.md
- docs/icons.md
- src/components/LinkItems/ItemIcon.vue
- src/utils/ConfigSchema.json
- src/utils/defaults.js
[![LinuxSBC](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/LinuxSBC/f73ae6)](https://github.com/LinuxSBC) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![LinuxSBC /master → Lissy93/dashy](https://badgen.net/badge/%231786/LinuxSBC%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 5 | Files Changed: 6 | Additions: 21](https://badgen.net/badge/New%20Code/Commits%3A%205%20%7C%20Files%20Changed%3A%206%20%7C%20Additions%3A%2021/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/1112165 …
> Add selfh.st/icons support

- src/components/Widgets/PublicIp.vue
[![s-weigand](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/s-weigand/f73ae6)](https://github.com/s-weigand) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![s-weigand /fix/typo-in-ip-api-provider-check → Lissy93/dashy](https://badgen.net/badge/%231869/s-weigand%20%2Ffix%2Ftypo-in-ip-api-provider-check%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix/typo-in-ip-api-provider-check) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00 …
> 🩹 Fix typo in Public Ip Widget endpoint definition for ip-api provider

- src/utils/defaults.js
[![he0119](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/he0119/f73ae6)](https://github.com/he0119) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![he0119 /fix/manifest → Lissy93/dashy](https://badgen.net/badge/%231868/he0119%20%2Ffix%2Fmanifest%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix/manifest) ![Commits: 3 | Files Changed: 1 | Additions: 8](https://badgen.net/badge/New%20Code/Commits%3A%203%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%208/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=g …
> Fix pwa conflicting/missing entries in cache list
