src/components/PageStrcture/Footer.vue

- Bugfix
**Issue Number** (if applicable): #42
**Briefly outline your changes**: Fixes issue with footer overlapping content. Does this by checking if page is scrollable, and only applying position fixed property if it is not.

Addresses #42 - Footer positioning bug

---

src/utils/Auth.js

**Category**: Bug Fix
Fixes expiry data passed to Auth token, so that it doesn't time out immediatley
#70
N/A
N/A

[BUG-FIX] Fixes error on login form timeout

---

README.md
docs/configuring.md
package.json
src/App.vue
src/styles/global-styles.scss
src/views/Login.vue
yarn.lock

**Category**: 
> One of:  Refactoring, Documentation and Bug Fix
**Overview**
- Updates docs, adds Snyk badge to readme, adds new sections, and login screenshot to readme, updates wording in Configuring
- Removes code from App.js, and adds in-code documentation
- Updates Prism.js to latest version, fixing #79 
- Bumps version to `1.3.7`
**Issue Number**  #79 

Refactor things n stuff

---

package.json
services/healthcheck.js
services/rebuild-app.js
src/components/Configuration/JsonEditor.vue
src/styles/color-themes.scss
yarn.lock

**Category**:  Refactoring
**Overview**
- Refactors Docker healthcheck script
- Adds in-code docs to rebiuld app server function
- Updates copy to include estimated built time after config write
- Makes vapourwave theme less ugly, fixes cyberpunk contrast ratio
- Upgrades dependencies
- Bumps to version 1.3.9

[REFACTOR] - Couple of quick tasks

---

Dockerfile-arm64v8

**Category**: 
Bugfix
**Overview**
Fixes `Dockerfile-arm64v8`. 
**Issue Number**  #117

Fix arm64v8 Dockerfile

---

src/assets/locales/fr.json

Hello,
**Category**: 
> Improvement
Overview
> Update fr.json for Dashy 1.5.6

Update fr.json for Dashy 1.5.6

---

package.json
src/components/Configuration/CustomCss.vue
src/components/Configuration/JsonEditor.vue

**Category**: One of: Bugfix
**Overview**
Started getting an error `error Missing file extension for 'xxx' import/extensions` thrown by ESLint. Unsure why, but likely misconfiguration. This PR correctly updates the ESLint config, which is for some reason, incorrectly stored in the package.json- i have no idea what it's doing there.

[FIX] ESLint Error - Disables import/extensions

---

Dockerfile

**Category**:  Docker
**Overview**
Sets the Docker base image to a fixed version of Node Alpine 3.14. This should hopefully prevent any unexpected changes, such as resource consumption, since everything will be pegged to a fixed version.
**Issue Number** #136

[DOCKER] Sets base image to alpine3.14 LTS

---

src/assets/locales/en.json
src/assets/locales/fr.json
src/components/LinkItems/ContextMenu.vue

Hello,
I modified Dashy in order to be able to offer a translation of the context menu.
I'm not used to this kind of modification, I was inspired by this for the realization : https://github.com/Lissy93/dashy/commit/8668621ca85a6da751e33f1308d17704e08a2af2
**Category**: 
> Improvement
**Screenshot** _(if applicable)_
In English : 
In French : 
- [X ] All changes are backwards compatible
- [X ] All lint checks and tests are passing
- [ X] There are no (new) build warnings or errors

Menu translate

---

.github/workflows/generate-credits.yml
README.md
docs/deployment.md
docs/quick-start.md
docs/troubleshooting.md

**Category**: Documentation
**Overview**
Adds a TLDR guide, updates readme, troubleshooting and GH actions

[DOCS] - Adds quick-start guide, and updates troubleshooting

---

.github/workflows/docker-publish.yml

**Category**: Build related changes
**Overview**
Write a script to run as a GH action, to build the Docker image, and then publish it to GitHub container registry through GH packages.
**Issue Number** #156

[DOCKER] [WIP] Action to build + publish Docker image to GHCR

---

Dockerfile

hi 👋🏼
I am going to be trying to update the dockerfile to make it more lightweight and support multiarch builds. I'll update the title when I am all set :)
Improvements:
- Adds [tini](https://github.com/krallin/tini) -  see [What is advantage of Tini?](https://github.com/krallin/tini/issues/8)
- Add `tzdata` which allows use of switch timezone via the `TZ` envar
- Use a multi-stage build to reduce Docker image size - maybe some more improvements to be made here. Ill leave that up for developers to figure out what's needed and what's not :)
- Allows use of multiple architectures

😎 Dockerfile Enhancements

---

src/views/Login.vue

**Overview**
Translations loaded when component mounts meant that other language files hadn't yet been loaded into memory, fixed in #129 a previous PR, but forgot to include the default dropdown option, which is what this one addresses
**Issue Number** #127

[FIX] Missing translation on Login screen

---

.github/workflows/docker-publish.yml
src/views/Login.vue

**Category**: Build related changes / Docker
**Overview**
Updating the GH action to build multi-architecture containers and push them to GHCR
**Issue Number** #158
**New Vars**
N/A
**Screenshot** 
N/A

[DOCKER] Action to build multi-architecture containers

---

src/assets/locales/fr.json

Hello :) ,
**Category**: 
> Improvement
Overview
> Update fr.json for Dashy 1.6.3

Update fr.json for Dashy 1.6.3

---

.github/workflows/docker-publish.yml

**Work in Progress, Do not Merge.**
**Category**:  Build related changes
**Overview**
**Issue Number** #158 

[DOCKER] Attempting automated multi-arch builds

---

README.md
docs/contributing.md
docs/showcase.md
docs/showcase/readme.md
docs/troubleshooting.md
src/components/Configuration/CustomCss.vue
src/components/Workspace/SideBar.vue
src/styles/color-themes.scss

**Category**: Refactoring Only
**Overview**
- Uses flex layout on style editor tab of config editor
- Fixes styles for Workspace view using Dashy theme
- Updates broken links in documentation + formating

[REFACTOR] - Style improvments

---

.github/CHANGELOG.md
package.json
public/default.html
src/assets/locales/en.json
src/components/Configuration/AppVersion.vue
src/components/Configuration/CloudBackupRestore.vue
src/components/Configuration/JsonEditor.vue
src/components/Configuration/RebuildApp.vue
src/components/Settings/ConfigLauncher.vue
src/components/Workspace/SideBar.vue
src/components/Workspace/SideBarItem.vue
src/styles/color-palette.scss
src/styles/color-themes.scss
yarn.lock

**Overview**
- During app initialization, show the build progress and status message
- While requests are being made, show loader at top of screen
- Also adds some UI improvements to Workspace view
**Screenshot**
This is the screen displayed while the app is building for the first time

[FEATURE] Better Loading UX

---

src/assets/locales/fr.json

Hello :) ,
**Category**: 
> Improvement
Overview
> Update fr.json for Dashy 1.6.8

Update fr for 1.6.8

---

src/assets/locales/fr.json

Hello, again  :) ,
**Category**: 
> Improvement
Overview
> Update fr.json for Dashy 1.6.9

Update fr.json for 1.6.9

---

.github/CHANGELOG.md
README.md
package.json

**Category**: Nothin Much
**Overview**
No real changed here, but have built a quick docs site, which is not linked to in the readme. Also bumps version ready for the Sunday 1.7 relase.

[UPDATE] - Launches Docs Site

---

.env
.github/CHANGELOG.md
.github/SECURITY.md
.github/workflows/issue-spam-control.yml
docs/icons.md
docs/privacy.md
package.json
services/print-message.js
src/components/LinkItems/ItemIcon.vue
src/styles/dimensions.scss
src/utils/defaults.js
vue.config.js

**Category**: Bugfix, Feature, Code style update, Refactoring, Build related changes, Documentation
**Overview**
- 12bd1c2 ⚡ Removes background in console art
- 51a45f2 🔧 Updates auto environmental variables
- e65d447 💄 Icon image assets max height #200
- e27cfc7 👔 Adds an action to close spammy issues
- d730c36 🔧 Adds option to enable SRI integrity, plus refactos PWA into defaults
- 94f935c 📝 Updates privacy and security docs
- b756e65 ✨ Adds option for different favicon API for each app #196
- 412c179 🐛 Fixes loading of local SVG icons #199
**Issue Number**
- Re: #196
- Re: #198
- Re: #199

[BUG-FIXES] - Minor UI bug fixes and build refactor

---

.github/pr-auto-comments.yml
.github/workflows/dependency-updates-summary.yml
.github/workflows/issue-spam-control.yml
.github/workflows/lgtm-comment.yml
.github/workflows/mind-your-language.yml
.github/workflows/pr-commenter.yml

**Category**:  Build related changes / automated repo administration
**Overview**
Adds actions to help with repository administration, and some just for fun :)

[BUILD] GH-actions for repository administration

---

src/assets/locales/fr.json

Hello :) ,
**Category**: 
> Improvement
Overview
> 🌐 Ajout traduction pour le sélecteur d'affichage

Update fr for 1.7.2 (View-switcher tooltip)

---

.github/.misspell-fixer.ignore
.github/workflows/docker-release.yml
src/components/Configuration/CustomCss.vue
src/components/Configuration/EditSiteMeta.vue
src/styles/global-styles.scss

**Category**: Minor Fix
**Overview**
- Fixes some minor typos
- Adds spell check ignore file, to ignore all non-english translation files

[FIX] Spelling

---

.github/CHANGELOG.md
docs/configuring.md
package.json
src/App.vue
src/components/Configuration/ConfigContainer.vue
src/components/Settings/ConfigLauncher.vue
src/components/Settings/LanguageSwitcher.vue
src/utils/ConfigAccumalator.js
src/utils/ErrorHandler.js

[![Lissy93 /REFACTOR/improved-language-detection → Lissy93/dashy](https://badgen.net/badge/%23223/Lissy93%20%2FREFACTOR%2Fimproved-language-detection%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/REFACTOR/improved-language-detection) ![Commits: 9 | Files Changed: 9 | Additions: 80](https://badgen.net/badge/New%20Code/Commits%3A%209%20%7C%20Files%20Changed%3A%209%20%7C%20Additions%3A%2080/dddd00) ![🚚 Refactor](https://badgen.net/badge/Type/%F0%9F%9A%9A%20Refactor/39b0fd) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)
**Category**: Refactoring
**Overview** …

[REFACTOR] Improved Language Detection

---

src/assets/locales/fr.json

**Category**: 
> Improvement
**Overview**
> Update fr.json for remember-me-long-time
- [ X] All changes are backwards compatible
- [ X] All lint checks and tests are passing
- [ X] There are no (new) build warnings or errors

✨ Ajout traduction "remember-me-long-time"

---

.github/LEGAL.md
.github/workflows/docs-link-checker.yml
docs/icons.md
src/components/FormElements/Button.vue
src/components/LinkItems/Item.vue
src/utils/MiscHelpers.js
src/views/Home.vue

**Category**: Refactoring Only
**Overview**
- Fixed some actions
- Updated icon docs
- Committed missed changes to Auto layout

[REFACTOR] Small changes I missed in the previous PR

---

src/components/MinimalView/MinimalSearch.vue
src/components/Settings/SearchBar.vue
src/utils/Search.js
src/views/Minimal.vue

[![Lissy93 /FIX/267-custom-search-engine → Lissy93/dashy](https://badgen.net/badge/%23269/Lissy93%20%2FFIX%2F267-custom-search-engine%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FIX/267-custom-search-engine) ![Commits: 3 | Files Changed: 4 | Additions: -112](https://badgen.net/badge/New%20Code/Commits%3A%203%20%7C%20Files%20Changed%3A%204%20%7C%20Additions%3A%20-112/dddd00) ![🐛 Fix](https://badgen.net/badge/Type/%F0%9F%90%9B%20Fix/39b0fd) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)
**Category**: Bug Fix
**Overview**
- 🐛 96f6a84 -  Fixes custom search …

[FIX] Custom search engine launching

---

docker-compose.yml
docs/deployment.md

Hello,
**Category**: 
Documentation 
**Overview**
In the documentation, added detached mode for docker-compose.
In docker-compose.yml, added detached mode in comment and added path to / app / public / item-icons

docker-compose / detached mode

---

src/styles/typography.scss

**Overview**
Adjusted/removed font class that was used in the editor that caused the pointer to not be displayed correctly.
Text is very slightly smaller and less bold.
**Issue Number** #124 
**Screenshot**
OLD | NEW

Config JSON Editor Pointer Fix

---

docs/configuring.md

[![Compunctus](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/Compunctus/f73ae6)](https://github.com/Compunctus) ![📕 Docs](https://badgen.net/badge/Type/%F0%9F%93%95%20Docs/39b0fd) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![Compunctus /patch-1 → Lissy93/dashy](https://badgen.net/badge/%23330/Compunctus%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00)
**Category**: 
Bugfix
**Overview**
Fixed typo …

configuring.md: fix keycloak type mismatch

---

README.md
docs/icons.md
package.json
src/components/Settings/SettingsContainer.vue
src/utils/defaults.js
yarn.lock

**Category**: Refactoring 
**Overview**
- Adds new favicon APIs
- Fixes hide settings option
- Shortens readme docs
- Updates dependencies
Here is [an example](https://user-images.githubusercontent.com/1862727/141648853-e342592e-8915-47ba-868e-4cdb49ab4847.png) of the different favicon APIs
- [] _(If a new dependency is added)_ Package is essential, and has been checked out for security or performance

[REFACTOR] Updates favicon fetching and docs

---

src/assets/locales/sl.json

[![UrekD](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/UrekD/f73ae6)](https://github.com/UrekD) ![🌐 Language Update](https://badgen.net/badge/Type/%F0%9F%8C%90%20Language%20Update/39b0fd) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![UrekD /master → Lissy93/dashy](https://badgen.net/badge/%23334/UrekD%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 75](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%2075/dddd00)
Some updates :) Have you been able to check for Crowdin integration?
**Category**: 
> Improvement
**Overview**
> Updated Slovenian locale

Updated Slovenian Locale

---

README.md

[![walkxcode](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/walkxcode/f73ae6)](https://github.com/walkxcode) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![walkxcode /patch-1 → Lissy93/dashy](https://badgen.net/badge/%23361/walkxcode%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 2 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
*Thank you for contributing to Dashy! So that your PR can be handled effectively, please populate the …

🛠️ Fix: Remove dashes in arch tags

---

README.md

[![walkxcode](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/walkxcode/f73ae6)](https://github.com/walkxcode) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![walkxcode /Grammer → Lissy93/dashy](https://badgen.net/badge/%23363/walkxcode%20%2FGrammer%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/Grammer) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
Your documentation may be grammatically correct, but sometimes it's wordy and hard to read. Walkx can help you! Try Walkxarly now at https://walkx.org! 😅 _(Grammarly reference)_
**Category**: 
> …

📝Fix grammer - Make easier to read🔀

---

.github/workflows/docker-image.yml

Merging into feature branch for testing

Docker Multi-Arch GH-Action

---

src/assets/locales/sv.json

[![BOZG](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/BOZG/f73ae6)](https://github.com/BOZG) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![BOZG /updated_swedish → Lissy93/dashy](https://badgen.net/badge/%23398/BOZG%20%2Fupdated_swedish%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/updated_swedish) ![Commits: 1 | Files Changed: 1 | Additions: 36](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%2036/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: 
> Improvement
**Overview**
> Added Swedish translations for new keys, minor improvements to existing. Sorry if the diff looks like a mess!
- [x ] All changes are …

Updated Swedish translation

---

src/components/Widgets/PublicHolidays.vue

[![XertDev](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/XertDev/f73ae6)](https://github.com/XertDev) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![XertDev /FIX/public-holidays-query-format → Lissy93/dashy](https://badgen.net/badge/%23418/XertDev%20%2FFIX%2Fpublic-holidays-query-format%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FIX/public-holidays-query-format) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
*Thank you for contributing to Dashy! So that your PR can be handled effectively, please populate the following fields (delete sections …

Query date formatting in PublicHolidays widget

---

README.md

[![b1thunt3r](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/b1thunt3r/f73ae6)](https://github.com/b1thunt3r) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![b1thunt3r /patch-1 → Lissy93/dashy](https://badgen.net/badge/%23424/b1thunt3r%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: 
> One of: Documentation
**Overview**
> Make it easier to read the `Searching and Shortcut` …

Fix formatting typo in README.md

---

.github/CHANGELOG.md
.github/LEGAL.md
docs/alternate-views.md
docs/configuring.md
docs/contributing.md
docs/credits.md
docs/developing.md
docs/development-guides.md
docs/privacy.md
docs/showcase.md
docs/troubleshooting.md
docs/widgets.md
package.json
src/components/LinkItems/Collapsable.vue
src/components/LinkItems/Section.vue
src/components/MinimalView/MinimalHeading.vue
src/components/MinimalView/MinimalSection.vue
src/components/Widgets/NewsHeadlines.vue
src/components/Widgets/WidgetBase.vue
src/components/Workspace/WebContent.vue
src/styles/color-palette.scss
src/styles/color-themes.scss
src/views/Minimal.vue

**Category**: Docs and Refactor
**Overview**
Lots of little updates to the docs
Improved theme support for widgets
Few other minor UI tasks

[REFACTOR] UI and docs updates

---

.github/CHANGELOG.md
.github/ISSUE_TEMPLATE/bug.yml
.github/workflows/manage-pending-labels.yml
README.md
docs/configuring.md
docs/showcase.md
docs/status-indicators.md
docs/troubleshooting.md
package.json
services/status-check.js
src/components/InteractiveEditor/EditItem.vue
src/components/LinkItems/Collapsable.vue
src/components/LinkItems/Item.vue
src/components/LinkItems/Section.vue
src/components/MinimalView/MinimalSection.vue
src/components/Widgets/CovidStats.vue
src/components/Widgets/NdCpuHistory.vue
src/components/Widgets/NdLoadHistory.vue
src/components/Widgets/NdRamHistory.vue
src/components/Widgets/WidgetBase.vue
src/styles/color-themes.scss
src/styles/dimensions.scss
src/styles/media-queries.scss
src/utils/ConfigSchema.json
src/views/Home.vue

This PR contains an updated Docker build script, plus a bunch of small fixes to be released in preparation for version 2.0.0
**Category**: Bugfix + Build related changes  + Docs
**Overview**
- 🐛 33b132c - Fixes full-height sections for mobile and Safari
- Re: #432
- Re: #442
- 🐛 488cfc1 - Fixes empty section visible in search
- Re: #447
- 🐛 6e2ae6d - Fixes numbers omited from tag names
- Re: #430
- ✨ e6ba324 - Option for custom status code in status check
- Re: #456 
- Re: #448
- 🌟 73c929c - Adds @stuu3k's dashboard to showcase
- Re: #446
- 🐛 5570cd2 - Switches recover and death count in Covid widget
- Re: #148
- 💄 34e109d - Improved contrast in light material theme
**Issue Number** #430, #432, #442, #447 #456
**Code Quality Checklist** _(Please …

[REFACTOR] Architectural Update and Small Fixes, for V 2.0.0

---

src/utils/MiscHelpers.js

[![rubenandre](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/rubenandre/f73ae6)](https://github.com/rubenandre) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![rubenandre /fix-putCommasInBigNum-utils → Lissy93/dashy](https://badgen.net/badge/%23468/rubenandre%20%2Ffix-putCommasInBigNum-utils%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix-putCommasInBigNum-utils) ![Commits: 1 | Files Changed: 1 | Additions: 1](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%201/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
*Thank you for contributing to Dashy! So that …

🐛 Fix putCommasInBigNum logic

---

server.js

**Category**: Error boundary
**Overview**
When the server starts, a welcome message is printed that contains some useful info, including hostname + IP.
This PR wraps that logic in a try/ catch block, incase Node throws an error while trying to fetch it.
**Issue Number** #477
- [-] Bumps version, if new feature added

[FIX] Adds try catch to server welcome msg

---

README.md

[![alexdelprete](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/alexdelprete/f73ae6)](https://github.com/alexdelprete) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![alexdelprete /master → Lissy93/dashy](https://badgen.net/badge/%23558/alexdelprete%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
*Thank you for contributing to Dashy! So that your PR can be handled effectively, please …

Updated Language Section (Italian)

---

docs/deployment.md

[![0n1cOn3](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/0n1cOn3/f73ae6)](https://github.com/0n1cOn3) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![0n1cOn3 /patch-1 → Lissy93/dashy](https://badgen.net/badge/%23567/0n1cOn3%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 19](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%2019/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: 
> One of: Bugfix / Feature / Code …

[Deployment Guide] Synology NAS installation steps

---

src/components/Settings/ThemeSelector.vue

[![emiran-orange](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/emiran-orange/f73ae6)](https://github.com/emiran-orange) ![🐛 Fix](https://badgen.net/badge/Type/%F0%9F%90%9B%20Fix/39b0fd) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![emiran-orange /cssthemes_in_dropdown → Lissy93/dashy](https://badgen.net/badge/%23619/emiran-orange%20%2Fcssthemes_in_dropdown%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/cssthemes_in_dropdown) ![Commits: 1 | Files Changed: 1 | Additions: 1](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%201/dddd00) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
**Overview**
Make user-defined …

[FIX] Make user-defined themes appear in drop-down list

---

src/assets/locales/pt.json

[![LeoColman](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/LeoColman/f73ae6)](https://github.com/LeoColman) ![🌐 Language Update](https://badgen.net/badge/Type/%F0%9F%8C%90%20Language%20Update/39b0fd) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![LeoColman /master → Lissy93/dashy](https://badgen.net/badge/%23625/LeoColman%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 132](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%20132/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265)
**Category**: 
Translations
**Overview**
I've reviewed all portuguese translations …

Finish PT translation

---

docs/authentication.md

[![Hellhium](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/Hellhium/f73ae6)](https://github.com/Hellhium) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![Hellhium /patch-1 → Lissy93/dashy](https://badgen.net/badge/%23652/Hellhium%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: 
> Documentation
**Overview**
> appConfig.enableGuestAccess should be …

fix guest access documentation

---

server.js

[![PlusaN](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/PlusaN/f73ae6)](https://github.com/PlusaN) ![🐛 Fix](https://badgen.net/badge/Type/%F0%9F%90%9B%20Fix/39b0fd) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![PlusaN /patch-1 → Lissy93/dashy](https://badgen.net/badge/%23671/PlusaN%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 3](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%203/dddd00) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
**Category**: 
Service startup changes
**Overview**
This is necessary in order to override which IP the Dashy process will bind to. …

Add HOST environment

---

docs/configuring.md

[![pinarruiz](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/pinarruiz/f73ae6)](https://github.com/pinarruiz) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![pinarruiz /patch-2 → Lissy93/dashy](https://badgen.net/badge/%23676/pinarruiz%20%2Fpatch-2%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-2) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
**Category**: 
> Documentation
**Overview**
> Typo on a word i found while reading the documentation.
**Code …

Fix: Typo on a word

---

yarn.lock

[![pinarruiz](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/pinarruiz/f73ae6)](https://github.com/pinarruiz) ![Large](https://badgen.net/badge/PR%20Size/Large/f4b546) [![pinarruiz /fix/update-yarn-lock → Lissy93/dashy](https://badgen.net/badge/%23698/pinarruiz%20%2Ffix%2Fupdate-yarn-lock%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix/update-yarn-lock) ![Commits: 1 | Files Changed: 1 | Additions: 576](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%20576/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
**Category**: 
> Fix
**Overview**
> Just updated yarn lock running …

[FIX] Update yarn.lock

---

docs/authentication.md
docs/configuring.md
src/components/Workspace/SideBar.vue
src/mixins/HomeMixin.js
src/utils/CheckItemVisibility.js
src/utils/CheckSectionVisibility.js
src/utils/ConfigSchema.json
src/utils/IsVisibleToUser.js

[![pinarruiz](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/pinarruiz/f73ae6)](https://github.com/pinarruiz) ![✨ Feature](https://badgen.net/badge/Type/%E2%9C%A8%20Feature/39b0fd) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![pinarruiz /feature/extend-visibility-items → Lissy93/dashy](https://badgen.net/badge/%23691/pinarruiz%20%2Ffeature%2Fextend-visibility-items%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/feature/extend-visibility-items) ![Commits: 14 | Files Changed: 8 | Additions: 150](https://badgen.net/badge/New%20Code/Commits%3A%2014%20%7C%20Files%20Changed%3A%208%20%7C%20Additions%3A%20150/dddd00)
**Category**: 
> Feature / Documentation
**Overview**
> Add support / extending keycloak and users visibility to section items. …

[FEATURE] Extend visibility to section items

---

src/assets/locales/zh-CN.json

[![zcq100](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/zcq100/f73ae6)](https://github.com/zcq100) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![zcq100 /master → Lissy93/dashy](https://badgen.net/badge/%23702/zcq100%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 137](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%20137/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: 
> Update Chinese translation
**Overview**
> Update Chinese translation
**Code Quality Checklist** 
- [ √ ] All changes are backwards compatible
- [ √ ] All lint checks and tests are passing
- [ √ ] There …

Update Chinese translation.

---

docs/management.md

[![pablomalo](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/pablomalo/f73ae6)](https://github.com/pablomalo) ![📕 Docs](https://badgen.net/badge/Type/%F0%9F%93%95%20Docs/39b0fd) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![pablomalo /patch-1 → Lissy93/dashy](https://badgen.net/badge/%23705/pablomalo%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265)
Thank you for this terrific documentation!!
**Category**: 
Documentation
**Overview**
hare => are

Fix typo in management.md

---

docs/readme.md

[![markusdd](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/markusdd/f73ae6)](https://github.com/markusdd) ![📕 Docs](https://badgen.net/badge/Type/%F0%9F%93%95%20Docs/39b0fd) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![markusdd /fix-TLDR-doc → Lissy93/dashy](https://badgen.net/badge/%23741/markusdd%20%2Ffix-TLDR-doc%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix-TLDR-doc) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265)
it ain't much, but it's honest work ;)
I think the change is kind of obious, for a quick start it …

Update readme.md - fix TDLR to TLDR ;)

---

src/components/Widgets/WidgetBase.vue

[![patrickheeney](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/patrickheeney/f73ae6)](https://github.com/patrickheeney) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![patrickheeney /FIX/Improve-Failed-Load → Lissy93/dashy](https://badgen.net/badge/%23759/patrickheeney%20%2FFIX%2FImprove-Failed-Load%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FIX/Improve-Failed-Load) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Overview**
Per [discussion](https://github.com/Lissy93/dashy/pull/758#discussion_r906049305) adding some …

:adhesive_bandage: Handle failed component load.

---

src/utils/defaults.js

[![dougaldhub](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/dougaldhub/f73ae6)](https://github.com/dougaldhub) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![dougaldhub /FEATURE/improve-tfl-widget → Lissy93/dashy](https://badgen.net/badge/%23766/dougaldhub%20%2FFEATURE%2Fimprove-tfl-widget%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FEATURE/improve-tfl-widget) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
*Thank you for contributing to Dashy! So that …

Update TFL Status Widget to include Elizabeth Line/Tram/DLR/Overground

---

docs/configuring.md
docs/widgets.md
src/components/LinkItems/Collapsable.vue
src/components/LinkItems/ItemIcon.vue
src/components/Widgets/WidgetBase.vue

**Overview**
- Adds option to add labels to widgets. Useful for identification, if there are multiple of the same type of widget in a single section.
- Adds section-name based class name to each section. Useful for custom themes.
**Issue Number** #769
**New Vars**
`widgets[].label` (string / optional)
**Screenshot** _(if applicable)_
N/A

[FEATURE] Option for labeled widgets

---

services/ssl-server.js

[![flechaig](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/flechaig/f73ae6)](https://github.com/flechaig) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![flechaig /patch-1 → Lissy93/dashy](https://badgen.net/badge/%23785/flechaig%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 2 | Files Changed: 1 | Additions: 2](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%202/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
Allow specifying a host on which to listen even with SSL
Grab the IP address from the HOST environment variable and …

Allow specifying a host on which to listen even with SSL

---

docs/widgets.md
src/assets/locales/en.json
src/components/Widgets/GluetunStatus.vue

**Category**: Refactoring
**Overview**
A few minor updates to the Gluetun Status widget, as the linting errors were causing build warnings.
- **Linted** (removes duplicate white space, double to single quotes, missing semmi colons, and string interprolation)
- **Internationalization**: Extracts hard-coded text into `en.json`
- **Error handling**: Handles missing options more elegantly, uses computed values for options
- If `hostname` is missing, show appropriate error message
- If `visibleFields` missing, default to public_ip, and updated docs
@jammo2k5 - If you get a moment, drop this PR a quick approval or review :)
**Issue Number** #808

[REFACTOR] Lint, error catching and translations for Gluetun Status Widget

---

src/components/LinkItems/Item.vue

[![miclav](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/miclav/f73ae6)](https://github.com/miclav) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![miclav /bug/periodic-check → Lissy93/dashy](https://badgen.net/badge/%23828/miclav%20%2Fbug%2Fperiodic-check%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/bug/periodic-check) ![Commits: 1 | Files Changed: 1 | Additions: 2](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%202/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: 
Bugfix
**Overview**
Before all items were requesting status checks even if status check wasn't enabled for them
That was creating lots of request to the backend for no …

Only do periodic check when statuscheck is enabled

---

src/utils/defaults.js

[![walkxcode](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/walkxcode/f73ae6)](https://github.com/walkxcode) ![🐛 Fix](https://badgen.net/badge/Type/%F0%9F%90%9B%20Fix/39b0fd) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![walkxcode /patch-1 → Lissy93/dashy](https://badgen.net/badge/%23851/walkxcode%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00)
**Category**: 
> One of: Other
**Overview**
> PR for #849 as requested.
**Issue Number** 
Completes #849 

🚚 Changes Dashboard Icons URL to new location

---

package.json
yarn.lock

[![maximemoreillon](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/maximemoreillon/f73ae6)](https://github.com/maximemoreillon) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![maximemoreillon /simple-icons-update → Lissy93/dashy](https://badgen.net/badge/%23885/maximemoreillon%20%2Fsimple-icons-update%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/simple-icons-update) ![Commits: 1 | Files Changed: 2 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
**Category**: Other: dependency update …

simple-icons update to v7.10.0

---

README.md

[![lxjv](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/lxjv/f73ae6)](https://github.com/lxjv) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![lxjv /master → Lissy93/dashy](https://badgen.net/badge/%23870/lxjv%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: 
> One of: fixing readme
**Overview**
> fixing the link to …

fixing dashboard icons link

---

src/components/Widgets/GlDiskSpace.vue

[![imlonghao](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/imlonghao/f73ae6)](https://github.com/imlonghao) ![🐛 Fix](https://badgen.net/badge/Type/%F0%9F%90%9B%20Fix/39b0fd) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![imlonghao /patch-1 → Lissy93/dashy](https://badgen.net/badge/%23880/imlonghao%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: -3](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%20-3/dddd00) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
*Thank you for contributing to Dashy! So that your PR can be handled effectively, please populate the following …

Fix widget GlDiskSpace 401 unauth

---

src/components/Widgets/Clock.vue

[![rubenandre](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/rubenandre/f73ae6)](https://github.com/rubenandre) ![🐛 Fix](https://badgen.net/badge/Type/%F0%9F%90%9B%20Fix/39b0fd) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![rubenandre /fix/issue-856 → Lissy93/dashy](https://badgen.net/badge/%23862/rubenandre%20%2Ffix%2Fissue-856%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix/issue-856) ![Commits: 1 | Files Changed: 1 | Additions: 4](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%204/dddd00)
**Category**: 
> Bugfix …

Fix issue #856

---

src/utils/defaults.js

[![nealian](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/nealian/f73ae6)](https://github.com/nealian) ![🚚 Refactor](https://badgen.net/badge/Type/%F0%9F%9A%9A%20Refactor/39b0fd) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![nealian /update_icons_versions → Lissy93/dashy](https://badgen.net/badge/%23874/nealian%20%2Fupdate_icons_versions%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/update_icons_versions) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00)
**Category**: 
> CDN references
**Overview**
> Update the two version-pinned icon "libraries" to load from their current versions: Simple Icons v7(.x), and Material Design …

⬆️ Updates optional external icons

---

src/components/Widgets/IframeWidget.vue

[![AaronPorts](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/AaronPorts/f73ae6)](https://github.com/AaronPorts) ![🐛 Fix](https://badgen.net/badge/Type/%F0%9F%90%9B%20Fix/39b0fd) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) ![✅ Ready](https://badgen.net/badge/Status/%E2%9C%85%20Ready/3ef963) [![AaronPorts /master → Lissy93/dashy](https://badgen.net/badge/%23871/AaronPorts%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00)
**Category**: 
> CSS
**Overview**
> Reduce min-height of iframe widget

IframeWidget min-height reduce to 80px

---

src/assets/locales/es.json

[![AmadeusGraves](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/AmadeusGraves/f73ae6)](https://github.com/AmadeusGraves) ![🌐 Language Update](https://badgen.net/badge/Type/%F0%9F%8C%90%20Language%20Update/39b0fd) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![AmadeusGraves /master → Lissy93/dashy](https://badgen.net/badge/%23899/AmadeusGraves%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 217](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%20217/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265)
Category:
Other (translation into spanish language)
Overview
Good …

Update Spanish Translation

---

docs/widgets.md
src/components/Widgets/Clock.vue

[![rtm516](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/rtm516/f73ae6)](https://github.com/rtm516) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![rtm516 /feature/12h-clock → Lissy93/dashy](https://badgen.net/badge/%23934/rtm516%20%2Ffeature%2F12h-clock%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/feature/12h-clock) ![Commits: 1 | Files Changed: 2 | Additions: 5](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%205/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265)
**Category**: 
> One of: …

Add 12 hour option to clock widget

---

services/healthcheck.js

[![thomasdissert](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/thomasdissert/f73ae6)](https://github.com/thomasdissert) ![🚚 Refactor](https://badgen.net/badge/Type/%F0%9F%9A%9A%20Refactor/39b0fd) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![thomasdissert /patch-1 → Lissy93/dashy](https://badgen.net/badge/%23964/thomasdissert%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 2 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00)
**Category**: 
Other: Comment updated
**Overview**
The code does not "create an HTTP server" but rather creates an HTTP request. That was fixed in the comment describing it
**Code …

Fixed comment describing healthcheck

---

src/assets/locales/ko.json

[![bskim45](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/bskim45/f73ae6)](https://github.com/bskim45) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![bskim45 /patch-1 → Lissy93/dashy](https://badgen.net/badge/%23940/bskim45%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 10](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%2010/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
**Category**: 
Other (update translation)
**Overview**
Updated Korean translations to fix some awkward expressions. …

Update Korean translations

---

docs/deployment.md

[![jrobles98](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/jrobles98/f73ae6)](https://github.com/jrobles98) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![jrobles98 /patch-1 → Lissy93/dashy](https://badgen.net/badge/%23986/jrobles98%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265)
*Thank you for contributing to Dashy! So that your PR can be handled effectively, please populate the following …

Update new pricing policy of Heroku

---

src/assets/locales/de.json

[![a-mnich](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/a-mnich/f73ae6)](https://github.com/a-mnich) ![🌐 Language Update](https://badgen.net/badge/Type/%F0%9F%8C%90%20Language%20Update/39b0fd) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![a-mnich /FIX/germanLocale → Lissy93/dashy](https://badgen.net/badge/%231030/a-mnich%20%2FFIX%2FgermanLocale%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/FIX/germanLocale) ![Commits: 1 | Files Changed: 1 | Additions: 38](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%2038/dddd00)
**Category**: 
Translation
**Overview**
Added missing german translations and fixed minor misspellings

Update German (de) locale

---

src/utils/MiscHelpers.js

**Overview**
The old endpoint (transferwise/currency-flags) was no longer available. Created a new repo ([Lissy93/currency-flags](https://github.com/Lissy93/currency-flags/)) which contain flag icons for (I think) each currency.
So this PR just updates the endpoint to point to my new repository.
**Issue Number** #1096
- [] _(If a new config option is added)_ Attribute is outlined in the schema and documented
- [] _(If a new dependency is added)_ Package is essential, and has been checked out for security or performance

[FIX] Updates the endpoint for currency flags

---

src/assets/locales/fr.json

[![EVOTk](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/EVOTk/f73ae6)](https://github.com/EVOTk) ![🌐 Language Update](https://badgen.net/badge/Type/%F0%9F%8C%90%20Language%20Update/39b0fd) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![EVOTk /master → Lissy93/dashy](https://badgen.net/badge/%231141/EVOTk%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 2 | Files Changed: 1 | Additions: 118](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%20118/dddd00) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=gi …

Update FR translation

---

src/mixins/GlancesMixin.js

[![poisonadder7](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/poisonadder7/f73ae6)](https://github.com/poisonadder7) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![poisonadder7 /master → Lissy93/dashy](https://badgen.net/badge/%231146/poisonadder7%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …

Update GlancesMixin.js - small typo correction

---

src/components/LinkItems/SubItem.vue

[![huangshaohuai](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/huangshaohuai/f73ae6)](https://github.com/huangshaohuai) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![huangshaohuai /huangshaohuai-dashy → Lissy93/dashy](https://badgen.net/badge/%231181/huangshaohuai%20%2Fhuangshaohuai-dashy%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/huangshaohuai-dashy) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …

get the correct tooltip for subitem

---

src/components/LinkItems/IframeModal.vue
src/components/Widgets/IframeWidget.vue
src/components/Workspace/WebContent.vue

**Category**: 
Feat
**Overview**
Updates the permissions for iframe widget, modal and workspace view. Allow nested sites to copy to system clipboard, when supported by the nested site.
**Issue Number** #1207

[Feature] Allow copy to clipboard within iframe

---

docs/widgets.md

[![Juoper](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/Juoper/f73ae6)](https://github.com/Juoper) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![Juoper /master → Lissy93/dashy](https://badgen.net/badge/%231229/Juoper%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lis …

Changed url from healthcheck.io to healthchecks.io

---

README.md
docs/deployment.md
docs/quick-start.md

[![berksmbl](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/berksmbl/f73ae6)](https://github.com/berksmbl) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![berksmbl /Add-Easypanel-Deployment-Method → Lissy93/dashy](https://badgen.net/badge/%231243/berksmbl%20%2FAdd-Easypanel-Deployment-Method%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/Add-Easypanel-Deployment-Method) ![Commits: 3 | Files Changed: 3 | Additions: 32](https://badgen.net/badge/New%20Code/Commits%3A%203%20%7C%20Files%20Changed%3A%203%20%7C%20Additions%3A%2032/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11e …

docs: Add Easypanel Deployment Method

---

src/components/Widgets/WeatherForecast.vue
src/utils/defaults.js

[![sachahjkl](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/sachahjkl/f73ae6)](https://github.com/sachahjkl) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![sachahjkl /fix/weather → Lissy93/dashy](https://badgen.net/badge/%231369/sachahjkl%20%2Ffix%2Fweather%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix/weather) ![Commits: 1 | Files Changed: 2 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …

fix(weather forecast): updated widget

---

src/utils/Search.js

[![deneor](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/deneor/f73ae6)](https://github.com/deneor) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![deneor /issue_1343 → Lissy93/dashy](https://badgen.net/badge/%231351/deneor%20%2Fissue_1343%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/issue_1343) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&ut …

[FIX] #1343 Search for items with cyrillic titles dosnt work

---

docs/development-guides.md

[![shazzx](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/shazzx/f73ae6)](https://github.com/shazzx) ![📕 Docs](https://badgen.net/badge/Type/%F0%9F%93%95%20Docs/39b0fd) [![shazzx /dashy-updated → Lissy93/dashy](https://badgen.net/badge/%231405/shazzx%20%2Fdashy-updated%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/dashy-updated) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https …

 [Docs] Improved minor errors in development-guides.md file

---

docs/widgets.md

[![edugof](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/edugof/f73ae6)](https://github.com/edugof) ![🐛 Fix](https://badgen.net/badge/Type/%F0%9F%90%9B%20Fix/39b0fd) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![edugof /patch-1 → Lissy93/dashy](https://badgen.net/badge/%231352/edugof%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11 …

Fix nextcloud widgets reference

---

docs/widgets.md

[![CrazyWolf13](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/CrazyWolf13/f73ae6)](https://github.com/CrazyWolf13) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![CrazyWolf13 /patch-1 → Lissy93/dashy](https://badgen.net/badge/%231428/CrazyWolf13%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" …

[Fix] Broken link

---

docs/widgets.md

[![CrazyWolf13](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/CrazyWolf13/f73ae6)](https://github.com/CrazyWolf13) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![CrazyWolf13 /patch-1 → Lissy93/dashy](https://badgen.net/badge/%231456/CrazyWolf13%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 2](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%202/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" …

[Add] Glances on Windows

---

src/components/LinkItems/Section.vue

[![CrazyWolf13](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/CrazyWolf13/f73ae6)](https://github.com/CrazyWolf13) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![CrazyWolf13 /revert-1275-bug/1274-popup-modal-fix → Lissy93/dashy](https://badgen.net/badge/%231464/CrazyWolf13%20%2Frevert-1275-bug%2F1274-popup-modal-fix%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/revert-1275-bug/1274-popup-modal-fix) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img …

Revert "bug #1274 multi page popup modal fix"

---

.editorconfig
LICENSE
README.md
docker/docker-readme.md
public/initialization.html
public/loading-screen.css
src/components/Configuration/AppInfoModal.vue
src/directives/ClickOutside.js
src/directives/LongPress.js
src/utils/Search.js
src/views/About.vue

[![CrazyWolf13](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/CrazyWolf13/f73ae6)](https://github.com/CrazyWolf13) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![CrazyWolf13 /fix_copyright_year → Lissy93/dashy](https://badgen.net/badge/%231473/CrazyWolf13%20%2Ffix_copyright_year%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix_copyright_year) ![Commits: 3 | Files Changed: 11 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%203%20%7C%20Files%20Changed%3A%2011%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …

updated copyright years

---

src/components/Widgets/Jokes.vue

[![markxoe](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/markxoe/f73ae6)](https://github.com/markxoe) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![markxoe /fix/jokes → Lissy93/dashy](https://badgen.net/badge/%231454/markxoe%20%2Ffix%2Fjokes%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix/jokes) ![Commits: 1 | Files Changed: 1 | Additions: 1](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%201/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …

Fix: Jokes of the day second line not deleted

---

docs/configuring.md

[![clsty](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/clsty/f73ae6)](https://github.com/clsty) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![clsty /patch-1 → Lissy93/dashy](https://badgen.net/badge/%231434/clsty%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00 …

Fixes on configuring.md

---

src/assets/locales/ar.json

[![alydemah](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/alydemah/f73ae6)](https://github.com/alydemah) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![alydemah /fix-locals-ar → Lissy93/dashy](https://badgen.net/badge/%231453/alydemah%20%2Ffix-locals-ar%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix-locals-ar) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?u …

Minor change in arabic locals

---

src/utils/ConfigHelpers.js

[![CrazyWolf13](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/CrazyWolf13/f73ae6)](https://github.com/CrazyWolf13) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![CrazyWolf13 /fix_hotkeys → Lissy93/dashy](https://badgen.net/badge/%231476/CrazyWolf13%20%2Ffix_hotkeys%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix_hotkeys) ![Commits: 3 | Files Changed: 2 | Additions: 1](https://badgen.net/badge/New%20Code/Commits%3A%203%20%7C%20Files%20Changed%3A%202%20%7C%20Additions%3A%201/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …

[Fix] Hotkeys

---

.github/workflows/update-docs-site.yml

**Category**:  Automation
**Overview**
Currently the docs site is manually synced with the docs from the master branch
This causes it to often be out-dated, which is annoying
This PR adds a workflow which syncs the docs from master to the website source, using @CrazyWolf13's Python script in [WEBSITE/docs-site-source/do-markdown-magic.py](https://github.com/Lissy93/dashy/blob/WEBSITE/docs-site-source/do-markdown-magic.py)
**Issue Number** ??

[FEAT] Adds a GH workflow automation to sync docs to docs site

---

docs/widgets.md

[![CrazyWolf13](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/CrazyWolf13/f73ae6)](https://github.com/CrazyWolf13) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![CrazyWolf13 /master → Lissy93/dashy](https://badgen.net/badge/%231505/CrazyWolf13%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 2 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …

Fixed typo's in uptime-kuma docs

---

src/assets/locales/pt.json

[![dyauss](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/dyauss/f73ae6)](https://github.com/dyauss) [![dyauss /master → Lissy93/dashy](https://badgen.net/badge/%231508/dyauss%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 10](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%2010/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Lissy93&utm_campaign=badge_info)
**Other (translation)**: …

Translation for gluetun status sentences in pt.json

---

src/assets/locales/pt.json

[![GuilhermeLCS95](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/GuilhermeLCS95/f73ae6)](https://github.com/GuilhermeLCS95) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![GuilhermeLCS95 /master → Lissy93/dashy](https://badgen.net/badge/%231509/GuilhermeLCS95%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 2 | Files Changed: 1 | Additions: 16](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%2016/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …

I added some translations to portuguese in pt.json

---

Dockerfile

[![CrazyWolf13](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/CrazyWolf13/f73ae6)](https://github.com/CrazyWolf13) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![CrazyWolf13 /master → Lissy93/dashy](https://badgen.net/badge/%231563/CrazyWolf13%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …

Revert start cmd Dockerfile

---

.devcontainer/devcontainer.json
.github/dependabot.yml
.gitignore
.vscode/launch.json
.vscode/tasks.json
vue.config.js

[![twsouthwick](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/twsouthwick/f73ae6)](https://github.com/twsouthwick) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![twsouthwick /devcontainer → Lissy93/dashy](https://badgen.net/badge/%231575/twsouthwick%20%2Fdevcontainer%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/devcontainer) ![Commits: 1 | Files Changed: 6 | Additions: 134](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%206%20%7C%20Additions%3A%20134/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" …

Add devcontainer support

---

docs/authentication.md

[![CrazyWolf13](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/CrazyWolf13/f73ae6)](https://github.com/CrazyWolf13) ![📕 Docs](https://badgen.net/badge/Type/%F0%9F%93%95%20Docs/39b0fd) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![CrazyWolf13 /master → Lissy93/dashy](https://badgen.net/badge/%231581/CrazyWolf13%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 21](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%2021/dddd00) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …

🧾 [docs](add) keycloak troubleshooting

---

docs/pages-and-sections.md

[![CrazyWolf13](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/CrazyWolf13/f73ae6)](https://github.com/CrazyWolf13) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![CrazyWolf13 /master → Lissy93/dashy](https://badgen.net/badge/%231601/CrazyWolf13%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 10](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%2010/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …

📝 Updated multi-page docs

---

src/components/LinkItems/Item.vue
src/styles/color-themes.scss
src/utils/defaults.js

**Category**: 
Theme
**Overview**
As requested by @sushibait, this theme is heavily inspired by that of NightTab.

🎨 New theme: NightBat

---

docs/deployment.md

[![ThibautSnoeijs](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/ThibautSnoeijs/f73ae6)](https://github.com/ThibautSnoeijs) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![ThibautSnoeijs /master → Lissy93/dashy](https://badgen.net/badge/%231658/ThibautSnoeijs%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …

Fixed a typo

---

src/styles/color-themes.scss

[![kt-alt](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/kt-alt/f73ae6)](https://github.com/kt-alt) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![kt-alt /fix/tama_dead_bkgUrl → Lissy93/dashy](https://badgen.net/badge/%231659/kt-alt%20%2Ffix%2Ftama_dead_bkgUrl%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix/tama_dead_bkgUrl) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullreques …

updated dead tama theme bkgUrl

---

docs/privacy.md
docs/widgets.md
src/components/Widgets/PublicIp.vue
src/utils/defaults.js

[![ip2location](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/ip2location/f73ae6)](https://github.com/ip2location) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![ip2location /master → Lissy93/dashy](https://badgen.net/badge/%231656/ip2location%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 4 | Additions: 11](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%204%20%7C%20Additions%3A%2011/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" …

Added support for IP2Location.io API

---

docs/privacy.md
docs/widgets.md
src/components/Widgets/WidgetBase.vue
src/utils/defaults.js

[![willbrowningme](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/willbrowningme/f73ae6)](https://github.com/willbrowningme) ![Medium](https://badgen.net/badge/PR%20Size/Medium/f3ff59) [![willbrowningme /anonaddy-to-addy-io → Lissy93/dashy](https://badgen.net/badge/%231637/willbrowningme%20%2Fanonaddy-to-addy-io%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/anonaddy-to-addy-io) ![Commits: 1 | Files Changed: 4 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%204%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-e …

Update AnonAddy to new addy.io branding

---

services/cors-proxy.js

Reverting a change made to cors-proxy in #1649
**Category**: 
> Bugfix 
**Overview**
> Briefly outline your new changes...
**Issue Number** _(if applicable)_ #1649
**New Vars** _(if applicable)_
> If you've added any new build scripts, environmental variables, config file options, dependency or devDependency, please outline here
**Screenshot** _(if applicable)_
> If you've introduced any significant UI changes, please include a screenshot

[REVERT] param change in cors-proxy.js

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/question.yml
.github/ISSUE_TEMPLATE/showcase-addition.yml

[![CrazyWolf13](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/CrazyWolf13/f73ae6)](https://github.com/CrazyWolf13) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![CrazyWolf13 /master → Lissy93/dashy](https://badgen.net/badge/%231686/CrazyWolf13%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 4 | Additions: -2](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%204%20%7C%20Additions%3A%20-2/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_m …

❌🐺 Update issue auto-assign

---

docs/icons.md

[![johnhorton2010](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/johnhorton2010/f73ae6)](https://github.com/johnhorton2010) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) ![✏️ Draft](https://badgen.net/badge/Status/%E2%9C%8F%EF%B8%8F%20Draft/ffa933) [![johnhorton2010 /fix-doc-typo → Lissy93/dashy](https://badgen.net/badge/%231703/johnhorton2010%20%2Ffix-doc-typo%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/fix-doc-typo) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/ …

Fix small doc typo

---

docs/widgets.md

[![lucolvin](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/lucolvin/f73ae6)](https://github.com/lucolvin) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![lucolvin /patch-1 → Lissy93/dashy](https://badgen.net/badge/%231709/lucolvin%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&u …

Fix typo in docs

---

docs/quick-start.md

[![sxravan](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/sxravan/f73ae6)](https://github.com/sxravan) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![sxravan /master → Lissy93/dashy](https://badgen.net/badge/%231852/sxravan%20%2Fmaster%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/master) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Category](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Category/f25265) ![Overview](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Overview/f25265) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265) …

Fixed one error in quick-start.md

---

docs/configuring.md

[![kit494way](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/kit494way/f73ae6)](https://github.com/kit494way) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![kit494way /update-docs-conf-pages → Lissy93/dashy](https://badgen.net/badge/%231864/kit494way%20%2Fupdate-docs-conf-pages%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/update-docs-conf-pages) ![Commits: 2 | Files Changed: 1 | Additions: 2](https://badgen.net/badge/New%20Code/Commits%3A%202%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%202/dddd00) ![Quality Checklist](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Quality%20Checklist/f25265) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) [<img width="16" alt="Powered by Pull Request Badge" …

Update docs conf pages

---

src/components/Widgets/GlNetworkInterfaces.vue

[![RobLoach](https://badgen.net/badge/%F0%9F%92%95%20Submitted%20by/RobLoach/f73ae6)](https://github.com/RobLoach) ![Quick](https://badgen.net/badge/PR%20Size/Quick/3eef8b) [![RobLoach /patch-1 → Lissy93/dashy](https://badgen.net/badge/%231752/RobLoach%20%2Fpatch-1%20%E2%86%92%20Lissy93%2Fdashy/ab5afc)](https://github.com/Lissy93/dashy/tree/patch-1) ![Commits: 1 | Files Changed: 1 | Additions: 0](https://badgen.net/badge/New%20Code/Commits%3A%201%20%7C%20Files%20Changed%3A%201%20%7C%20Additions%3A%200/dddd00) ![Label](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FMissing/Label/f25265) ![Unchecked Tasks](https://badgen.net/badge/%E2%9A%A0%EF%B8%8FNotice/Unchecked%20Tasks/f25265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/11121652 …

🩹 Fix compilation warning on comment
